import 'server-only';
import sharp from 'sharp';
import {HttpError} from './server';
sharp.concurrency(1);sharp.cache({memory:32,files:0,items:20});
export async function preparePhotos(files:File[]){if(files.length>3)throw new HttpError(400,'Upload up to three photos.');const output:Buffer[]=[];for(const file of files){
 if(!file.size||file.size>5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type))throw new HttpError(400,'Photos must be JPEG, PNG or WebP, up to 5 MB each.');
 try{const bytes=Buffer.from(await file.arrayBuffer());const input=sharp(bytes,{limitInputPixels:40_000_000,failOn:'error'});const meta=await input.metadata();if(!['jpeg','png','webp'].includes(meta.format||'')||(meta.pages||1)>1)throw new Error('Invalid image');output.push(await input.rotate().resize(1600,1600,{fit:'inside',withoutEnlargement:true}).webp({quality:85}).toBuffer());}catch{throw new HttpError(400,'One photo could not be read. Use a standard JPEG, PNG or WebP image.');}
}return output;}
function json(raw:string){try{return JSON.parse(raw);}catch{throw new HttpError(400,'Invalid application data.');}}
export async function applicationBody(req:Request){const reader=req.body?.getReader();if(!reader)throw new HttpError(400,'Missing application');const chunks:Uint8Array[]=[];let size=0;for(;;){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>16*1024*1024){await reader.cancel();throw new HttpError(413,'Application is too large.');}chunks.push(value);}const bytes=Buffer.concat(chunks);if(req.headers.get('content-type')?.startsWith('multipart/form-data')){let form:FormData;try{form=await new Response(bytes,{headers:{'Content-Type':req.headers.get('content-type')!}}).formData();}catch{throw new HttpError(400,'Invalid upload. Please reselect your photos and try again.');}const raw=form.get('application');if(typeof raw!=='string'||raw.length>30000)throw new HttpError(400,'Invalid application');const files=form.getAll('photos');if(files.some(f=>typeof f==='string'))throw new HttpError(400,'Invalid photos');return {data:json(raw),files:files as File[]};}if(bytes.length>30000)throw new HttpError(413,'Application is too large.');return {data:json(bytes.toString()),files:[] as File[]};}
