'use client';
import {useState,type FormEvent} from 'react';
import {useRouter} from 'next/navigation';
type Values=Record<string,string|number|null>;
const labels:Record<string,string>={first_name:'First name',last_name:'Last name',display_name:'Display name',date_of_birth:'Date of birth',email:'Email',phone:'Phone',instagram:'Instagram',city:'City',gym:'Gym',height:'Height (inches)',current_weight:'Weight (lb)',years_boxing:'Years boxing',amateur_fights:'Amateur fights',professional_fights:'Professional fights',sparring_experience:'Sparring experience',availability:'Availability',video_url:'Footage link',boxrec_url:'BoxRec link',notes:'Applicant notes',emergency_name:'Emergency contact',emergency_phone:'Emergency phone',guardian_name:'Guardian name',guardian_contact:'Guardian contact'};
const options={stance:['Orthodox','Southpaw','Switch'],skill_level:['Beginner','Developing','Intermediate','Advanced','Competitive amateur','Professional'],preferred_intensity:['Technical/light','Controlled/moderate','Competitive technical']};
export default function ApplicationEditor({values,id,version}:{values:Values;id:string;version:number}){const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const router=useRouter();
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage('');const data={...Object.fromEntries(new FormData(e.currentTarget)),id,version};try{const r=await fetch('/api/admin/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'EDIT_APPLICATION',data})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage('Saved. The change log records this correction. Review before republishing the profile.');setOpen(false);router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}}
 return <section className="admin-card"><button type="button" className="button outline" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'CLOSE EDITOR':'EDIT APPLICATION'}</button>{message&&<p role="status">{message}</p>}{open&&<form onSubmit={save}><p>Correct contact and boxing details. Consents, payment status and guardian approval cannot be granted here. Changes are logged and return the public profile for review.</p><div className="form-grid">{Object.entries(labels).map(([key,label])=><label key={key}>{label}<input name={key} defaultValue={values[key]??''} type={key==='date_of_birth'?'date':key==='email'?'email':['height','current_weight','years_boxing','amateur_fights','professional_fights'].includes(key)?'number':'text'} step={key==='height'||key==='current_weight'||key==='years_boxing'?'any':undefined} maxLength={key==='notes'?3000:1500}/></label>)}{Object.entries(options).map(([key,items])=><label key={key}>{key.replaceAll('_',' ')}<select name={key} defaultValue={String(values[key]||'')}>{items.map(o=><option key={o}>{o}</option>)}</select></label>)}</div><label>Reason for editing<textarea name="reason" required minLength={3} maxLength={500}/></label><div className="actions"><button className="button red" disabled={busy}>{busy?'SAVING…':'SAVE CORRECTIONS'}</button><button type="button" className="button outline" disabled={busy} onClick={()=>setOpen(false)}>CANCEL</button></div></form>}</section>;
}
