import Link from 'next/link';
import {db,result,dbReady} from '../lib/server';
import {requireAdmin} from '../lib/admin-page';
import AdminForm,{Logout} from './admin-form';
import Matchmaker from './matchmaker';
import {ageFromDob} from '../lib/application';
export const dynamic='force-dynamic';
export const metadata={title:'Operations',robots:{index:false,follow:false}};
export default async function Admin({searchParams}:{searchParams:Promise<Record<string,string>>}){
 await requireAdmin();const q=await searchParams;
 const [ar,sr,mr,or,nr]=await Promise.all([db().from('applications').select('*,fighters(*)').order('created_at',{ascending:false}).limit(1000),db().from('sessions').select('*').order('date',{ascending:false}),db().from('matchups').select('*').order('created_at',{ascending:false}).limit(500),db().from('orders').select('*').order('created_at',{ascending:false}).limit(1000),db().from('notification_outbox').select('id,recipient,subject,attempts,last_error').is('sent_at',null).limit(100)]);
 const subscribers=result(await db().from('subscribers').select('id,first_name,email,created_at,subscribed').order('created_at',{ascending:false}).limit(1000));
 const all=result(ar),sessions=result(sr),matches=result(mr),orders=result(or),pending=result(nr);
 const apps=all.filter(a=>{const f=a.fighters;const age=ageFromDob(f.date_of_birth)??f.age;return (!q.search||`${f.first_name} ${f.last_name} ${f.display_name} ${f.email}`.toLowerCase().includes(q.search.toLowerCase()))&&(!q.status||a.application_status===q.status)&&(!q.session||a.session_id===q.session)&&(!q.gym||f.gym.toLowerCase().includes(q.gym.toLowerCase()))&&(!q.stance||f.stance===q.stance)&&(!q.skill||f.skill_level===q.skill)&&(!q.experience||f.competition_experience===q.experience)&&(!q.minWeight||f.current_weight>=Number(q.minWeight))&&(!q.maxWeight||f.current_weight<=Number(q.maxWeight))&&(!q.minAge||age>=Number(q.minAge))&&(!q.maxAge||age<=Number(q.maxAge));});
 return <div className="shell workspace"><div className="workspace-title"><div><p className="eyebrow">PUNCH OPERATIONS</p><h1>THE ROUNDS DESK.</h1></div><Logout/></div><p>{dbReady()?'Database connected.':''} {all.length} applications · {pending.length} queued emails. Lists display the latest 1,000 applications/orders and 500 matchups.</p>
 <nav className="workspace-nav"><a href="#applications">APPLICATIONS</a><a href="#matchmaking">MATCHMAKING</a><a href="#sessions">SESSIONS</a><a href="#matches">MATCHUPS & CONTENT</a><a href="#notifications">NOTIFICATIONS</a></nav>
 <section id="applications"><h2>APPLICATIONS.</h2><form className="filter-grid" method="get"><label>Search<input name="search" defaultValue={q.search}/></label>{['minWeight','maxWeight','minAge','maxAge'].map(n=><label key={n}>{({minWeight:'Weight from (lb)',maxWeight:'Weight to (lb)',minAge:'Age from',maxAge:'Age to'})[n]}<input name={n} type="number" min="0" defaultValue={q[n]}/></label>)}<label>Gym<input name="gym" defaultValue={q.gym}/></label>{[['status',['NEW','REVIEWING','WAITLIST','MATCHED','CONFIRMED','COMPLETED','DECLINED','CANCELLED']],['stance',['Orthodox','Southpaw','Switch']],['experience',['No fights','Amateur','Professional']],['skill',['Beginner','Developing','Intermediate','Advanced','Competitive amateur','Professional']]].map(([name,values])=><label key={String(name)}>{String(name)}<select name={String(name)} defaultValue={q[String(name)]}><option value="">All</option>{(values as string[]).map(v=><option key={v}>{v}</option>)}</select></label>)}<label>Session<select name="session" defaultValue={q.session}><option value="">All</option>{sessions.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><button className="button red">FILTER</button><Link href="/admin" className="button outline">RESET</Link><a href="/api/admin/export" className="button outline">EXPORT ALL CSV</a></form>
 <div className="table-scroll"><table><thead><tr>{['Name','Age','Weight','Height','Stance','Experience','Gym','Instagram','Session','Status','Content','Created'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{apps.map(a=>{const f=a.fighters;return <tr key={a.id}><td><Link href={`/admin/applications/${a.id}`}>{f.display_name}</Link>{a.guardian_required&&<small>GUARDIAN {a.guardian_reviewed_at?'REVIEWED':'REQUIRED'}</small>}</td><td>{ageFromDob(f.date_of_birth)}</td><td>{f.current_weight} lb</td><td>{f.height} in</td><td>{f.stance}</td><td>{f.years_boxing} yrs · {f.skill_level}</td><td>{f.gym}</td><td>{f.instagram}</td><td>{sessions.find(s=>s.id===a.session_id)?.title||'Any'}</td><td>{a.application_status}</td><td>{orders.some(o=>o.fighter_id===f.id&&o.payment_status==='PAID')?'CONTENT PAID ✓':'NO CONTENT PACK'}</td><td>{a.created_at.slice(0,10)}</td></tr>;})}</tbody></table>{apps.length===0&&<p>No matching applications.</p>}</div></section>
 <section id="matchmaking"><h2>BUILD THE MATCHUP.</h2><Matchmaker candidates={all.filter(a=>['NEW','REVIEWING','WAITLIST'].includes(a.application_status))} sessions={sessions.filter(s=>s.status==='UPCOMING')}/></section>
 <section id="sessions"><h2>PUNCH SESSIONS.</h2><div className="record-list">{sessions.map(s=><article key={s.id}><b>{s.title}</b><p>{s.date} · {s.start_time} · {s.location_name} · {s.status} · {s.is_public?'PUBLIC':'DRAFT'}</p><AdminForm action="SESSION_STATUS" fixed={{id:s.id}} label="UPDATE SESSION"><select name="status" defaultValue={s.status}><option>UPCOMING</option><option>COMPLETED</option></select></AdminForm></article>)}</div><details><summary>CREATE SESSION</summary><AdminForm action="SESSION" label="CREATE SESSION"><div className="form-grid">{[['title','Title','text'],['slug','URL slug (punch-session-001)','text'],['date','Date','date'],['start_time','Start time (Los Angeles)','time'],['location_name','Location name','text'],['city','City','text'],['protected_location_field','Private address — invitees only','text']].map(([name,label,type])=><label key={name}>{label}<input name={name} type={type} required/></label>)}<label>Description<textarea name="description"/></label><label className="check-row"><input type="checkbox" name="is_public"/><span>Publish this session page</span></label></div></AdminForm></details></section>
 <section id="matches"><h2>MATCHUPS & CONTENT.</h2>{matches.map(m=>{const a=all.find(a=>a.fighter_id===m.fighter_a_id)?.fighters,b=all.find(a=>a.fighter_id===m.fighter_b_id)?.fighters;return <article className="record-card" key={m.id}><h3>{a?.display_name||'Fighter A'} × {b?.display_name||'Fighter B'}</h3><p>{sessions.find(s=>s.id===m.session_id)?.title} · {m.rounds} × {m.round_length}s · {m.status} · {m.published?'PUBLISHED':'UNPUBLISHED'}</p><p>{m.internal_notes}</p><div className="inline-actions">{['COMPLETE','CANCEL','PUBLISH'].map(action=><AdminForm key={action} action="MATCHUP_STATUS" label={action} fixed={{id:m.id,action}}/>)}</div>{orders.filter(o=>o.matchup_id===m.id).map(o=><div className="notice" key={o.id}><b>{o.fighter_id===m.fighter_a_id?a?.display_name:b?.display_name}: {o.payment_status==='PAID'?'CONTENT PAID ✓':o.payment_status}</b><p>{o.content_status} · ${(o.amount/100).toFixed(2)}{o.amount_refunded>0?` · Refunded $${o.amount_refunded/100}`:''}</p>{m.status==='CANCELLED'&&o.payment_status==='PAID'&&<p>REFUND REVIEW REQUIRED — process a refund in Stripe; the webhook updates this order.</p>}<AdminForm action="CONTENT" fixed={{id:o.id}} label="UPDATE DELIVERY"><select name="content_status" defaultValue={o.content_status}>{['NOT_STARTED','EDITING','DELIVERED'].map(s=><option key={s}>{s}</option>)}</select></AdminForm></div>)}<details><summary>ATTACH VIDEO</summary><AdminForm action="MEDIA" fixed={{matchup_id:m.id}} label="SAVE VIDEO"><label>Title<input name="title" required/></label><label>HTTPS video URL<input name="url" type="url" required/></label><label>Type<select name="kind"><option>FULL_ROUNDS</option><option>HIGHLIGHT</option><option>SOCIAL_REEL</option></select></label><label>Fighter<select name="fighter_id"><option value="">Both fighters</option><option value={m.fighter_a_id}>{a?.display_name}</option><option value={m.fighter_b_id}>{b?.display_name}</option></select></label><label className="check-row"><input name="published" type="checkbox"/><span>Publish approved media</span></label></AdminForm></details></article>;})}</section>
 <section id="subscribers"><h2>UPDATES SUBSCRIBERS.</h2><a className="button outline" href="/api/admin/export?type=subscribers">EXPORT OPT-IN EMAILS</a><div className="table-scroll"><table><thead><tr><th>Name</th><th>Email</th><th>Subscribed</th><th>Date</th></tr></thead><tbody>{subscribers.map(s=><tr key={s.id}><td>{s.first_name}</td><td>{s.email}</td><td>{s.subscribed?'YES':'NO'}</td><td>{s.created_at.slice(0,10)}</td></tr>)}</tbody></table></div></section><section id="notifications"><h2>NOTIFICATIONS.</h2><p>Queued emails remain here if delivery fails. Database records are saved independently.</p>{pending.map(n=><p key={n.id}>{n.subject} · {n.recipient} · Attempts: {n.attempts} {n.last_error}</p>)}<AdminForm action="RETRY_EMAILS" label="RETRY QUEUED EMAILS"/></section></div>;
}

