'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import Image from 'next/image';
import PhotoPicker from './photo-picker';
export default function ProfilePhotos({fighterId,photos,avatar,cover,version,token}:{fighterId:string;photos:{id:string}[];avatar:string|null;cover:string|null;version:number;token?:string}){
 const router=useRouter();const [keep,setKeep]=useState(photos.map(p=>p.id)),[files,setFiles]=useState<File[]>([]),[a,setA]=useState(avatar?.split('/').pop()||''),[c,setC]=useState(cover?.split('/').pop()||''),[urls,setUrls]=useState<Record<string,string>>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;const created:string[]=[];Promise.all(photos.map(async p=>{const r=await fetch('/api/photos/'+p.id,{headers:token?{Authorization:'Bearer '+token}:{},cache:'no-store'});if(!r.ok)throw new Error();const url=URL.createObjectURL(await r.blob());created.push(url);return [p.id,url];})).then(p=>{if(active)setUrls(Object.fromEntries(p));else created.forEach(u=>URL.revokeObjectURL(u));}).catch(()=>{if(active)setMessage('Some photos could not be loaded. Reload or request a new editing link.');});return()=>{active=false;created.forEach(u=>URL.revokeObjectURL(u));};},[photos,token]);
 const options=[...keep.map((id,i)=>({id,label:`Existing photo ${i+1}`})),...files.map((_,i)=>({id:`new:${i}`,label:`New photo ${i+1}`}))];
 async function save(){setBusy(true);setMessage('');try{const form=new FormData();form.set('application',JSON.stringify({fighter_id:fighterId,version,keep,avatar:a||null,cover:c||null}));files.forEach(f=>form.append('photos',f));const r=await fetch(token?'/api/profile/photos':'/api/admin/photos',{method:'POST',headers:token?{Authorization:'Bearer '+token}:{},body:form});const d=await r.json();if(!r.ok)throw new Error(d.error);setFiles([]);setMessage('Saved. Your photos and profile are awaiting organizer review before public display.');router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'Could not save photos.');}finally{setBusy(false);}}
 return <div className="profile-photo-editor"><p>Up to three photos. Choose an avatar and a separate cover. Saving changes sends the profile back for organizer review.</p><div className="photo-selection">{keep.map((id,i)=><figure key={id}>{urls[id]&&<Image unoptimized src={urls[id]} width={180} height={140} alt={`Existing photo ${i+1}`}/>}<figcaption>Photo {i+1}</figcaption><button type="button" className="button outline" disabled={busy} onClick={()=>{setKeep(keep.filter(p=>p!==id));if(a===id)setA('');if(c===id)setC('');}}>REMOVE PHOTO {i+1}</button></figure>)}</div><PhotoPicker files={files} disabled={busy} limit={3-keep.length} onChange={f=>{setFiles(f);if(a.startsWith('new:'))setA('');if(c.startsWith('new:'))setC('');}}/><div className="form-grid"><label>Avatar<select value={a} onChange={e=>setA(e.target.value)}><option value="">No avatar</option>{options.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label><label>Profile cover<select value={c} onChange={e=>setC(e.target.value)}><option value="">No cover</option>{options.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label></div><button type="button" disabled={busy} className="button red" onClick={save}>{busy?'SAVING…':'SAVE PHOTOS'}</button>{message&&<p role="status">{message}</p>}</div>;
}
