'use client';
import {useRef,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {requestId} from '../lib/request-id';
export default function ServiceRequestForm({kind,open}:{kind:'HIGHLIGHT_EDIT'|'PRIVATE_SHOOT';open:boolean}){
 const id=useRef('');const [busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setBusy(true);if(!id.current)id.current=requestId();const form=e.currentTarget;const values=Object.fromEntries(new FormData(form));try{const res=await fetch('/api/service-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,kind,request_id:id.current,rights_confirmed:values.rights_confirmed==='on'})});const data=await res.json();if(!res.ok)throw Error(data.error||'Unable to save request.');setDone(true);}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
 if(!open)return <p className="notice">Online requests are temporarily closed. <a href="mailto:farukhimin@gmail.com">Email the organizer</a> to discuss your project.</p>;
 if(done)return <div className="notice" role="status"><h2>REQUEST RECEIVED.</h2><p>We’ll review your request and contact you by email to discuss the material, scope and price. Nothing is booked or charged yet.</p><p>{kind==='HIGHLIGHT_EDIT'?'If you don’t have footage ready, we’ll explain what we need. If the request is outside our scope, we’ll let you know.':'We’ll confirm location, availability and deliverables with you before booking.'}</p><Link href="/sessions" className="button outline">EXPLORE SESSIONS →</Link></div>;
 return <form onSubmit={submit} className="service-request-form"><div className="form-grid"><label>Name<input name="name" autoComplete="name" required maxLength={160}/></label><label>Email<input name="email" type="email" autoComplete="email" required maxLength={254}/></label><label>Instagram (optional)<input name="instagram" autoCapitalize="none" placeholder="@yourhandle" maxLength={200}/></label>{kind==='HIGHLIGHT_EDIT'?<><label>What would you like?<select name="edit_type"><option>Personal highlight</option><option>Social reel</option><option>Both — separate edits</option></select></label><label>Footage link (optional)<input name="source_url" type="url" placeholder="https://" maxLength={1500}/></label><label>Our session / source details (optional)<input name="session_reference" maxLength={500} placeholder="Session name, or let us know footage isn’t ready"/></label></>:<><label>Type of shoot<select name="shoot_type"><option>Training session</option><option>Fighter story / interview</option><option>Fight preparation</option><option>Social content</option><option>Other</option></select></label><label>City / gym<input name="location" required maxLength={300}/></label><label>Preferred date or range<input name="preferred_dates" required maxLength={200} placeholder="e.g. November weekends / flexible"/></label><label>Budget (optional)<input name="budget" maxLength={150} placeholder="Your range, if known"/></label></>}</div><label>Tell us what you have in mind<textarea name="brief" required maxLength={3000} rows={4}/></label>{kind==='HIGHLIGHT_EDIT'&&<label className="check-row"><input name="rights_confirmed" type="checkbox" required/><span>I have permission to provide any material I share for editing. This request does not give permission to publish it.</span></label>}<label className="honeypot" aria-hidden="true">Leave empty<input name="website" tabIndex={-1} autoComplete="off"/></label><p className="fine">We use these details to respond to your request. This does not subscribe you to marketing. <Link href="/privacy">Privacy notice</Link>. Scope and price are confirmed before payment.</p>{error&&<p role="alert" className="form-error">{error}</p>}<button className="button red" disabled={busy}>{busy?'SAVING…':kind==='HIGHLIGHT_EDIT'?'REQUEST AN EDIT →':'REQUEST A SHOOT →'}</button></form>;
}
