'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {track} from '../../lib/analytics';
export default function Controls({token,confirmed,bothConfirmed,paid,closed}:{token:string;confirmed:boolean;bothConfirmed:boolean;paid:boolean;closed:boolean}){
 const router=useRouter();const [busy,setBusy]=useState(false),[error,setError]=useState(''),[declinedPack,setDeclinedPack]=useState(false);
 async function act(action:'confirm'|'decline'|'checkout'){
  setBusy(true);setError('');try{const r=await fetch(action==='checkout'?'/api/checkout':'/api/match/respond',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,accept:action==='confirm'})});const d=await r.json();if(!r.ok)throw new Error(d.error);if(action==='checkout'){track('checkout_started');location.assign(d.url);}else{if(action==='confirm')track('match_confirmed');router.refresh();}}catch(e){setError(e instanceof Error?e.message:'Unable to save. Please try again.');}finally{setBusy(false);}
 }
 if(closed)return <p className="notice">This matchup is closed. Contact the organizer if you need help.</p>;
 return <div>{error&&<p role="alert" className="form-error">{error}</p>}{!confirmed?<div className="actions"><button className="button red" disabled={busy} onClick={()=>act('confirm')}>CONFIRM MY SPOT</button><button className="button outline" disabled={busy} onClick={()=>act('decline')}>I CAN’T MAKE IT</button></div>:<><p className="notice"><b>YOUR SPOT IS CONFIRMED.</b> {bothConfirmed?'Both fighters have confirmed.':'Waiting for your partner’s confirmation. We will update this page.'}</p>{paid?<p className="notice"><b>CONTENT PAID ✓</b> Your payment has been verified.</p>:declinedPack?<p role="status">No Content Pack selected. Your participation remains confirmed.</p>:<section className="content-offer"><p className="eyebrow">OPTIONAL / FOUNDING PRICE</p><h2>PUNCH CONTENT PACK.</h2><p className="pack-price">$99 <small>USD / fighter</small></p><ul><li><b>FULL ROUNDS</b> — Professional multicamera edit of your complete sparring session.</li><li><b>PERSONAL HIGHLIGHT</b> — Best sequences centered on you.</li><li><b>SOCIAL REEL</b> — Vertical edit ready for Instagram/TikTok.</li><li><b>PUNCH PROFILE</b> — Session added to your documented Punch record.</li></ul><p>Purchasing content is optional. It does not affect eligibility or participation.</p>{!bothConfirmed&&<p>Checkout opens once both fighters have confirmed.</p>}<div className="actions"><button disabled={busy||!bothConfirmed} className="button red" onClick={()=>act('checkout')}>ADD CONTENT PACK — $99</button><button className="button outline" onClick={()=>setDeclinedPack(true)}>NO THANKS — I’LL JUST SPAR</button></div></section>}<details><summary>Need to cancel your participation?</summary><p>The pairing will be cancelled and the organizer will need to arrange a replacement. Any paid pack requires refund review.</p><button className="button outline" disabled={busy} onClick={()=>act('decline')}>I CAN’T MAKE IT</button></details></>}</div>;
}
