'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {track} from '../../lib/analytics';
export default function Controls({token,confirmed,bothConfirmed,paid,closed,terms,termsVersion,paymentsOpen}:{token:string;confirmed:boolean;bothConfirmed:boolean;paid:boolean;closed:boolean;terms:string;termsVersion:number;paymentsOpen:boolean}){
 const [emergencyName,setEmergencyName]=useState(''),[emergencyPhone,setEmergencyPhone]=useState('');
 const [acceptedTerms,setAcceptedTerms]=useState(false);
 const router=useRouter();const [busy,setBusy]=useState(false),[error,setError]=useState(''),[declinedPack,setDeclinedPack]=useState(false);
 async function act(action:'confirm'|'decline'|'checkout'){
  setBusy(true);setError('');try{const r=await fetch(action==='checkout'?'/api/checkout':'/api/match/respond',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,accept_terms:acceptedTerms,terms_version:termsVersion,accept:action==='confirm',emergency_name:emergencyName,emergency_phone:emergencyPhone})});const d=await r.json();if(!r.ok)throw new Error(d.error);if(action==='checkout'){track('checkout_started');location.assign(d.url);}else{if(action==='confirm')track('match_confirmed');router.refresh();}}catch(e){setError(e instanceof Error?e.message:'Unable to save. Please try again.');}finally{setBusy(false);}
 }
 if(closed)return <p className="notice">This matchup is closed. Contact the organizer if you need help.</p>;
 return <div>{error&&<p role="alert" className="form-error">{error}</p>}{!confirmed?<div><p>Before confirming, add an emergency contact for this session.</p><div className="form-grid"><label>Emergency contact name<input name="emergency_name" value={emergencyName} onChange={e=>setEmergencyName(e.target.value)} maxLength={150}/></label><label>Emergency contact phone<input name="emergency_phone" type="tel" value={emergencyPhone} onChange={e=>setEmergencyPhone(e.target.value)} maxLength={40}/></label></div><div className="actions"><button className="button red" disabled={busy} onClick={()=>act('confirm')}>CONFIRM MY SPOT</button><button className="button outline" disabled={busy} onClick={()=>act('decline')}>I CAN’T MAKE IT</button></div></div>:<><p className="notice"><b>YOUR SPOT IS CONFIRMED.</b> {bothConfirmed?'Both fighters have confirmed.':'Waiting for your partner’s confirmation. We will update this page.'}</p>{paid?<p className="notice"><b>CONTENT PAID ✓</b> Your payment has been verified.</p>:declinedPack?<p role="status">No Content Pack selected. Your participation remains confirmed.</p>:<section className="content-offer"><p className="eyebrow">OPTIONAL / FOUNDING PRICE</p><h2>PUNCH CONTENT PACK.</h2><p className="pack-price">$99 <small>USD / fighter</small></p><ul><li><b>YOUR SPARRING RECORDING</b> — Edited recording of one agreed matchup.</li><li><b>SHARED VERTICAL REEL</b> — One highlights reel featuring both fighters.</li><li><b>THREE CORRECTION ROUNDS</b> — Within the agreed scope; files through Google Drive.</li></ul><p>A personal highlight focused on you is a separate service.</p>{terms?<div className="notice"><h3>YOUR ORDER DETAILS</h3><p style={{whiteSpace:'pre-wrap'}}>{terms}</p><label className="check-row"><input type="checkbox" checked={acceptedTerms} onChange={e=>setAcceptedTerms(e.target.checked)}/><span>I agree to these order details, delivery and cancellation terms.</span></label></div>:<p className="notice">The organizer will confirm the scope, delivery date and order terms before payment opens.</p>}{!paymentsOpen&&<p className="notice">Online payment is not open yet. Your sparring place is unaffected.</p>}<p>Purchasing content is optional. It does not affect eligibility or participation.</p>{!bothConfirmed&&<p>Checkout opens once both fighters have confirmed.</p>}<div className="actions"><button disabled={busy||!bothConfirmed||!paymentsOpen||!acceptedTerms||!terms} className="button red" onClick={()=>act('checkout')}>ADD CONTENT PACK — $99</button><button className="button outline" onClick={()=>setDeclinedPack(true)}>NO THANKS — I’LL JUST SPAR</button></div></section>}<details><summary>Need to cancel your participation?</summary><p>The pairing will be cancelled and the organizer will need to arrange a replacement. Any paid pack requires refund review.</p><button className="button outline" disabled={busy} onClick={()=>act('decline')}>I CAN’T MAKE IT</button></details></>}</div>;
}
