import Link from 'next/link';
import {db,invitation,result} from '../../lib/server';
import Controls from './controls';
import EventBeacon from '../../components/event-beacon';
export const dynamic='force-dynamic';
export const metadata={title:'Your Punch invitation',robots:{index:false,follow:false},referrer:'no-referrer' as const};
export default async function Match({params,searchParams}:{params:Promise<{token:string}>;searchParams:Promise<{payment?:string}>}){
 const {token}=await params;const query=await searchParams;
 let data;try{data=await invitation(token);}catch{return <div className="shell workspace narrow"><h1>INVITATION UNAVAILABLE.</h1><p>This link is invalid, expired, or temporarily unavailable. Contact the organizer for help.</p></div>;}
 const {c,m}=data;const opponent=m.fighter_a_id===c.fighter_id?m.fighter_b_id:m.fighter_a_id;
 const [sr,fr,or]=await Promise.all([db().from('sessions').select('title,date,start_time,timezone,location_name,protected_location_field,city,status').eq('id',m.session_id).single(),db().from('fighters').select('display_name,current_weight,stance,years_boxing,skill_level').eq('id',opponent).single(),db().from('orders').select('payment_status,content_status,amount_refunded').eq('fighter_id',c.fighter_id).eq('matchup_id',m.id).maybeSingle()]);
 const s=result(sr),f=result(fr);if(or.error)throw new Error('Unable to load order');const paid=or.data?.payment_status==='PAID';
 return <div className="shell workspace narrow"><EventBeacon name="match_confirmation_viewed"/>{paid&&<EventBeacon name="content_pack_purchased"/>}<p className="eyebrow">YOUR PRIVATE INVITATION</p><h1>YOU’VE BEEN MATCHED.</h1><h2>{s.title}</h2><p>{s.date} · {s.start_time} ({s.timezone})</p><p>{s.location_name} · {s.city}</p><p>{s.protected_location_field}</p><div className="record-card"><p className="eyebrow">YOUR SPARRING PARTNER</p><h2>{f.display_name}</h2><p>Approximately {Math.round(f.current_weight/5)*5} lb · {f.stance}</p><p>{f.years_boxing} years boxing · {f.skill_level}</p><p>{m.rounds} rounds × {m.round_length} seconds</p></div><p>Technical sparring. Headgear and mouthguard required. 16 oz gloves by default; 14 oz only with coach approval. Either fighter or the coach/referee can stop the round. Final pairing and readiness checks take place on site.</p><p><Link href="/terms">Read session rules</Link></p>{query.payment==='processing'&&!paid&&<p className="notice">Payment is being verified. This redirect is not a payment receipt. Refresh this page shortly to check the confirmed status.</p>}{query.payment==='cancelled'&&<p className="notice">Checkout cancelled. Your participation is unchanged.</p>}{or.data?.payment_status==='REFUNDED'&&<p className="notice">Your Content Pack has been refunded.</p>}<Controls token={token} confirmed={c.status==='CONFIRMED'} bothConfirmed={m.status==='CONFIRMED'} paid={paid} terms={m.content_terms||''} termsVersion={m.content_terms_version||0} paymentsOpen={process.env.PAYMENTS_OPEN==='true'} closed={['CANCELLED','COMPLETED'].includes(m.status)||s.status!=='UPCOMING'||c.status==='DECLINED'}/></div>;
}
