import {test,expect} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
test.skip(!process.env.VPS_QA,'Explicit live test only');
test('live contact capture, conversion, retry and admin privacy',async({page,request},info)=>{
 const email=`vps-qa-v4-${info.project.name}-${Date.now()}@example.com`;
 await page.goto('/apply?utm_source=qa&utm_campaign=v4');await page.locator('[name=first_name]').fill('QA');await page.locator('[name=email]').fill(email);await page.locator('[name=phone]').fill('2025550123');
 await page.getByLabel('Month',{exact:true}).selectOption('04');await page.getByLabel('Day',{exact:true}).selectOption('12');await page.getByLabel('Year',{exact:true}).selectOption('1995');
 const leadResponse=page.waitForResponse(r=>r.url().endsWith('/api/leads'));await page.getByRole('button',{name:'CONTINUE'}).click();expect((await leadResponse).status()).toBe(200);
 const stored=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('punch-application-v4')!).data);const origin=new URL(process.env.QA_BASE_URL!).origin;
 const denied=await request.post('/api/leads',{headers:{Origin:origin},data:{...stored,lead_token:'a'.repeat(64)}});expect(denied.status()).toBe(403);
 await page.reload();await page.locator('[name=city]').fill('Los Angeles');await page.locator('[name=height]').selectOption('70');await page.locator('[name=current_weight]').fill('175');await page.locator('[name=years_boxing]').fill('3');await page.locator('[name=stance]').selectOption('Orthodox');await page.locator('[name=skill_level]').selectOption('Intermediate');await page.locator('[name=sparring_experience]').selectOption('Weekly');await page.locator('[name=preferred_intensity]').selectOption('Technical/light');await page.getByLabel('Weekend mornings',{exact:true}).check();await page.getByText('Add more details (optional)',{exact:true}).click();await page.locator('[name=professional_fights]').fill('2');
 await page.getByRole('button',{name:'CONTINUE'}).click();await page.locator('[name=rules_accepted]').check();await page.locator('[name=content_accepted]').check();await page.locator('input[type=file]').setInputFiles(path.resolve('public/video/poster-v4.jpg'));
 const submitted=page.waitForResponse(r=>r.url().endsWith('/api/applications'));await page.getByRole('button',{name:'SUBMIT APPLICATION'}).click();const response=await submitted;expect(response.status()).toBe(201);const {id}=await response.json();await expect(page.getByText('APPLICATION RECEIVED.',{exact:true})).toBeVisible();
 const original=response.request().postDataBuffer()!;const retry=await request.post('/api/applications',{headers:{Origin:origin,'Content-Type':response.request().headers()['content-type']},data:original});expect(retry.status()).toBe(201);expect((await retry.json()).id).toBe(id);
 expect((await request.get('/admin')).status()).toBe(404);expect((await request.get('/api/admin/export?type=leads')).status()).toBe(404);
 await page.goto('http://100.102.7.5:3100/admin/login');const credentials=fs.readFileSync(process.env.VPS_ADMIN_FILE!,'utf8');await page.locator('[name=email]').fill('farukhimin@gmail.com');await page.locator('[name=password]').fill(credentials.match(/Password: (.+)/)![1].trim());await page.getByRole('button',{name:'SIGN IN',exact:true}).click();await expect(page).toHaveURL(/\/admin$/);
 const lead=page.locator('#leads tr').filter({hasText:email});await expect(lead).toContainText('Completed');await expect(lead).toContainText('NO OPT-IN');await expect(lead).toContainText('v4');
 await page.goto(`http://100.102.7.5:3100/admin/applications/${id}`);await expect(page.locator('h1')).toHaveText('QA');const photo=page.locator('.photo-gallery img');await expect(photo).toHaveCount(1);const src=await photo.getAttribute('src');expect((await request.get(src!)).status()).toBe(404);
 await page.goto(`http://100.102.7.5:3100/admin?a=${id}#matchmaking`);await expect(page.locator('[name=application_a_id]')).toHaveValue(id);await expect(page.locator('.comparison').first()).toContainText('Weekly');await expect(page.locator('.comparison').first()).toContainText('Weekend mornings');
 await page.screenshot({path:`../infra-staging/v4-admin-${info.project.name}.png`,fullPage:true});
});
