import Link from 'next/link';
import {notFound} from 'next/navigation';
import {requireAdmin} from '../../../lib/admin-page';
import {db,result} from '../../../lib/server';
import ApplicationEditor from '../../application-editor';
import ProfilePhotos from '../../../components/profile-photos';
import CopyLink from '../../../components/copy-link';
import {origin} from '../../../lib/server';
import AdminForm from '../../admin-form';
import {sql} from '../../../lib/postgres';
import Image from 'next/image';
import MediaPlayer from '../../../components/media-player';
export const dynamic='force-dynamic';
export default async function ApplicationDetail({params}:{params:Promise<{id:string}>}){
 await requireAdmin();const {id}=await params;if(!/^[a-f0-9-]{36}$/.test(id))notFound();
 const {data:a,error}=await db().from('applications').select('*,fighters(*)').eq('id',id).maybeSingle();if(error)throw new Error('Unable to load application');if(!a)notFound();const f=a.fighters;
 const history=result(await db().from('matchups').select('id,session_id,status,rounds').or(`fighter_a_id.eq.${f.id},fighter_b_id.eq.${f.id}`));
 const photos=(await sql().query('SELECT id FROM fighter_photos WHERE fighter_id=$1 ORDER BY position',[f.id])).rows;
 const videos=(await sql().query('SELECT * FROM profile_media WHERE fighter_id=$1 ORDER BY created_at DESC',[f.id])).rows;
 const audit=(await sql().query("SELECT l.*,coalesce(l.actor_label,u.email,'System / legacy action') AS editor FROM audit_log l LEFT JOIN admin_users u ON u.id=l.actor WHERE l.entity_id IN ($1,$2) ORDER BY l.created_at DESC LIMIT 100",[id,f.id])).rows;
 const height=Number(f.height);const heightLabel=`${Math.floor(height/12)}′${height%12}″ (${Math.round(height*2.54)} cm)`;
 const groups:Record<string,Record<string,unknown>>={
 'Contact':{'Legal name':`${f.first_name} ${f.last_name}`,'Email':f.email,'Phone':f.phone,'Instagram':f.instagram,'City':f.city,'Emergency contact':f.emergency_name,'Emergency phone':f.emergency_phone},
 'Boxing':{'Age':f.age,'Height':heightLabel,'Weight':`${f.current_weight} lb`,'Stance':f.stance,'Gym':f.gym,'Years boxing':f.years_boxing,'Competition':f.competition_experience,'Amateur fights':f.amateur_fights,'Professional fights':f.professional_fights,'Skill level':f.skill_level,'Sparring experience':f.sparring_experience},
 'Application':{'Received':new Date(a.created_at).toLocaleString('en-US',{timeZone:'America/Los_Angeles',dateStyle:'medium',timeStyle:'short'}),'Availability':a.availability,'Intensity':a.preferred_intensity,'Applicant notes':f.notes||a.additional_notes,'Visibility':f.visibility,'Media permission':a.media_consent?'Granted':'Not granted','Participation rules':a.rules_accepted?'Accepted':'Not accepted','Guardian review':a.guardian_required?(a.guardian_reviewed_at?'Completed':'Required'):'Not required',...(a.guardian_required?{'Guardian':a.guardian_name,'Guardian contact':a.guardian_contact}:{})}
 };
 return <div className="shell workspace admin-workspace"><Link className="admin-back" href="/admin">← All applications</Link><header className="applicant-header">{photos[0]&&<Image unoptimized src={`/api/photos/${photos[0].id}`} width={88} height={88} alt="Applicant portrait"/>}<div><p className="eyebrow">FIGHTER APPLICATION</p><h1>{f.display_name}</h1><p>{f.gym} · {f.current_weight} lb · {f.stance}</p></div><span className="status-badge">{a.application_status.replaceAll('_',' ')}</span></header>
 <nav className="workspace-nav"><a href="#details">DETAILS</a><a href="#review">REVIEW & NOTES</a><a href="#photos">PHOTOS</a><a href="#profile">PROFILE & VIDEO</a></nav>
 <ApplicationEditor key={f.edit_version} id={id} version={f.edit_version} values={{...f,availability:a.availability,preferred_intensity:a.preferred_intensity,guardian_name:a.guardian_name,guardian_contact:a.guardian_contact}}/><div id="details" className="applicant-details">{Object.entries(groups).map(([title,fields])=><section className="admin-card" key={title}><h2>{title}</h2><table className="detail-table"><tbody>{Object.entries(fields).map(([label,value])=><tr key={label}><th scope="row">{label}</th><td>{String(value??'—')||'—'}</td></tr>)}</tbody></table></section>)}</div>
 <div className="inline-actions admin-links">{f.video_url&&<a href={f.video_url} target="_blank" rel="noreferrer">VIEW FOOTAGE ↗</a>}{f.boxrec_url&&<a href={f.boxrec_url} target="_blank" rel="noreferrer">BOXREC PROFILE ↗</a>}{f.instagram&&<a href={`https://www.instagram.com/${encodeURIComponent(f.instagram.replace(/^@/,''))}/`} target="_blank" rel="noreferrer">INSTAGRAM ↗</a>}</div>
 <h2 id="review">Review & notes</h2><AdminForm action={['MATCHED','CONFIRMED','COMPLETED'].includes(a.application_status)?'NOTES':'APPLICATION'} fixed={{id}}><label>Internal notes<textarea name="internal_notes" defaultValue={a.internal_notes} maxLength={5000}/></label>{!['MATCHED','CONFIRMED','COMPLETED'].includes(a.application_status)&&<label>Status<select name="application_status" defaultValue={a.application_status}>{['NEW','REVIEWING','WAITLIST','DECLINED','CANCELLED'].map(v=><option key={v}>{v}</option>)}</select></label>}</AdminForm>
 {a.guardian_required&&<div className="notice"><h3>GUARDIAN REVIEW</h3><p>Verify guardian authority and required participation documentation outside this form. Record the reference and reviewer notes before clearing for manual matching.</p>{a.guardian_reviewed_at?<p>Reviewed {a.guardian_reviewed_at}: {a.guardian_review_notes}</p>:<AdminForm action="GUARDIAN" fixed={{id}} label="RECORD COMPLETED GUARDIAN REVIEW"><label>Evidence / document reference and notes<textarea name="notes" minLength={15} required/></label></AdminForm>}</div>}
 <h2 id="photos">Photographs</h2><ProfilePhotos key={f.photo_version} fighterId={f.id} photos={photos} avatar={f.profile_photo_url} cover={f.cover_photo_url} version={f.photo_version}/>
 <h2 id="profile">Public profile</h2><AdminForm action="PROFILE" fixed={{id:f.id,photo_version:f.photo_version,edit_version:f.edit_version}}><label>Avatar<select name="profile_photo_url" defaultValue={f.profile_photo_url||''}><option value="">No avatar</option>{photos.map((p,i)=><option key={p.id} value={`/api/photos/${p.id}`}>Photo {i+1}</option>)}{f.profile_photo_url&&!f.profile_photo_url.startsWith('/api/photos/')&&<option value={f.profile_photo_url}>Existing portrait</option>}</select></label><label className="check-row"><input name="profile_published" type="checkbox" defaultChecked={f.profile_published}/><span>Publish adult profile with verified media consent</span></label></AdminForm><p>Public address — available only after publication approval:</p><CopyLink url={`${origin()}/fighter/${f.public_slug}`}/><p>Fighters can request their private photo editing link at <Link href="/profile/access">/profile/access</Link>.</p>
 <h2>Profile videos</h2><p>Add a YouTube or Vimeo link. Video files are hosted by the provider, not uploaded here. Draft videos are visible only in this dashboard.</p>{videos.map(v=><div key={v.id}><p>{v.published?'PUBLIC':'DRAFT'}</p><MediaPlayer url={v.url} title={v.title}/><AdminForm action="REMOVE_PROFILE_VIDEO" fixed={{id:v.id}} label="REMOVE VIDEO"/></div>)}<AdminForm action="PROFILE_VIDEO" fixed={{id:f.id}} label="ADD VIDEO"><label>Title<input name="title" required maxLength={150}/></label><label>Video HTTPS link<input name="url" type="url" required/></label><label className="check-row"><input name="published" type="checkbox"/><span>Publish on this fighter’s approved Public profile</span></label><label className="check-row"><input name="permission_confirmed" type="checkbox"/><span>I verified publication permission from everyone shown in this footage.</span></label></AdminForm>
 <h2>Change log</h2><p>Latest 100 actions. Times shown in Los Angeles time.</p>{audit.length===0?<p>No recorded changes.</p>:audit.map(entry=><details className="admin-card" key={entry.id}><summary>{new Date(entry.created_at).toLocaleString('en-US',{timeZone:'America/Los_Angeles'})} · {entry.editor} · {entry.action.replaceAll('_',' ')}</summary>{entry.changes?.reason&&<p>Reason: {entry.changes.reason}</p>}<table className="detail-table"><thead><tr><th>Field</th><th>Before</th><th>After</th></tr></thead><tbody>{Object.entries(entry.changes?.fields||entry.changes||{}).filter(([key])=>key!=='reason').map(([key,value])=>{const change=value as {before:unknown;after:unknown};return <tr key={key}><th>{key.replaceAll('_',' ')}</th><td>{JSON.stringify(change.before??null)}</td><td>{JSON.stringify(change.after??null)}</td></tr>;})}</tbody></table></details>)}<h2>Punch history</h2>{history.map(h=><p key={h.id}>{h.status} · {h.rounds} rounds · Session {h.session_id}</p>)}</div>;
}
