import Link from 'next/link';
import {notFound} from 'next/navigation';
import {requireAdmin} from '../../../lib/admin-page';
import {db,result} from '../../../lib/server';
import AdminForm from '../../admin-form';
export const dynamic='force-dynamic';
export default async function ApplicationDetail({params}:{params:Promise<{id:string}>}){
 await requireAdmin();const {id}=await params;if(!/^[a-f0-9-]{36}$/.test(id))notFound();
 const {data:a,error}=await db().from('applications').select('*,fighters(*)').eq('id',id).maybeSingle();if(error)throw new Error('Unable to load application');if(!a)notFound();const f=a.fighters;
 const history=result(await db().from('matchups').select('id,session_id,status,rounds').or(`fighter_a_id.eq.${f.id},fighter_b_id.eq.${f.id}`));
 return <div className="shell workspace"><Link href="/admin">← OPERATIONS</Link><h1>{f.display_name}</h1><h2>APPLICATION DETAIL.</h2><div className="compare-grid"><dl>{Object.entries(f).filter(([k])=>!['id','public_slug'].includes(k)).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{String(v??'—')}</dd></div>)}</dl><div><dl>{Object.entries(a).filter(([k])=>!['fighters','fighter_id','id','request_id','internal_notes'].includes(k)).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{String(v??'—')}</dd></div>)}</dl>{f.video_url&&<p><a href={f.video_url} target="_blank" rel="noreferrer">VIEW FOOTAGE ↗</a></p>}{f.instagram&&<p><a href={`https://www.instagram.com/${encodeURIComponent(f.instagram.replace(/^@/,''))}/`} target="_blank" rel="noreferrer">INSTAGRAM ↗</a></p>}</div></div><h2>REVIEW.</h2><AdminForm action={['MATCHED','CONFIRMED','COMPLETED'].includes(a.application_status)?'NOTES':'APPLICATION'} fixed={{id}}><label>Internal notes<textarea name="internal_notes" defaultValue={a.internal_notes} maxLength={5000}/></label>{!['MATCHED','CONFIRMED','COMPLETED'].includes(a.application_status)&&<label>Status<select name="application_status" defaultValue={a.application_status}>{['NEW','REVIEWING','WAITLIST','DECLINED','CANCELLED'].map(v=><option key={v}>{v}</option>)}</select></label>}</AdminForm>
 {a.guardian_required&&<div className="notice"><h3>GUARDIAN REVIEW</h3><p>Verify guardian authority and required participation documentation outside this form. Record the reference and reviewer notes before clearing for manual matching.</p>{a.guardian_reviewed_at?<p>Reviewed {a.guardian_reviewed_at}: {a.guardian_review_notes}</p>:<AdminForm action="GUARDIAN" fixed={{id}} label="RECORD COMPLETED GUARDIAN REVIEW"><label>Evidence / document reference and notes<textarea name="notes" minLength={15} required/></label></AdminForm>}</div>}
 <h2>PUBLIC PROFILE.</h2><AdminForm action="PROFILE" fixed={{id:f.id}}><label>Approved portrait HTTPS URL<input type="url" name="profile_photo_url" defaultValue={f.profile_photo_url||''}/></label><label className="check-row"><input name="profile_published" type="checkbox" defaultChecked={f.profile_published}/><span>Publish adult profile with verified media consent</span></label></AdminForm><p>Public URL: <Link href={`/fighter/${f.public_slug}`}>/fighter/{f.public_slug}</Link></p><h2>PUNCH HISTORY.</h2>{history.map(h=><p key={h.id}>{h.status} · {h.rounds} rounds · Session {h.session_id}</p>)}</div>;
}
