'use client';
import {useRef,useState,type FormEvent} from 'react';
import Link from 'next/link';
import HeightSelect from '../components/height-select';
import {ageFromDob} from '../lib/application';
import {track} from '../lib/analytics';
import {applicationSchema} from '../lib/validation';
import {useApplicationDraft} from '../lib/use-application-draft';
import {requestId as makeRequestId} from '../lib/request-id';
export default function ApplicationForm({sessions,sessionId,open}:{sessions:{id:string;title:string;date:string}[];sessionId:string;open:boolean}){
 const [step,setStep]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[received,setReceived]=useState(false);
 const [d,setD]=useState<Record<string,string|boolean>>({session_id:sessionId,amateur_fights:'0',professional_fights:'0',visibility:'PRIVATE',media_consent:false,competition_experience:'No fights',website:''});
 const requestId=useRef('');const started=useRef(false);const heading=useRef<HTMLHeadingElement>(null);
 const [photos,setPhotos]=useState<File[]>([]);
 const draft=useApplicationDraft('punch-application-mvp-v1',d,step,received,(saved,savedStep)=>{setD(old=>({...old,...saved}));setStep(savedStep);requestId.current=String(saved.request_id||'');},2);
 const age=ageFromDob(String(d.date_of_birth||'')),youth=age!==null&&age<18;
 function update(key:string,value:string|boolean){if(!started.current){track('application_started');started.current=true;}setD(old=>({...old,[key]:value}));setError('');}
 function field(key:string,label:string,type='text',required=true,min?:number,max?:number){return <label key={key}>{label}{required?' *':' (optional)'}<input name={key} type={type} required={required} min={min} max={max} maxLength={1000} step={type==='number'?'any':undefined} value={String(d[key]??'')} onChange={e=>update(key,e.target.value)}/></label>;}
 function select(key:string,label:string,options:string[]){return <label>{label} *<select name={key} required value={String(d[key]||'')} onChange={e=>update(key,e.target.value)}><option value="">Select</option>{options.map(o=><option key={o}>{o}</option>)}</select></label>;}
 function area(key:string,label:string,required=true){return <label className="full">{label}{required?' *':' (optional)'}<textarea name={key} required={required} maxLength={3000} value={String(d[key]||'')} onChange={e=>update(key,e.target.value)} rows={3}/></label>;}
 function consent(key:string,label:React.ReactNode){return <label className="check-row"><input type="checkbox" name={key} required checked={Boolean(d[key])} onChange={e=>update(key,e.target.checked)}/><span>{label}</span></label>;}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');if(step<2){if(step===0&&age===null){setError('Enter a valid date of birth.');return;}setStep(step+1);setTimeout(()=>heading.current?.focus(),0);return;}
  if(!requestId.current){requestId.current=makeRequestId();setD(old=>({...old,request_id:requestId.current}));}
  const parsed=applicationSchema.safeParse({...d,request_id:requestId.current,visibility:youth?'PRIVATE':d.visibility,media_consent:youth||d.visibility==='PRIVATE'?false:d.media_consent});
  if(!parsed.success){setError(parsed.error.issues[0].message);return;}
  setBusy(true);try{const form=new FormData();form.set('application',JSON.stringify(parsed.data));photos.forEach(p=>form.append('photos',p));const r=await fetch('/api/applications',{method:'POST',body:form});const data=await r.json();if(!r.ok)throw new Error(data.error);setReceived(true);track('application_submitted');}catch(e){setError(e instanceof Error?e.message:'Unable to submit. Please try again.');}finally{setBusy(false);}
 }
 if(received)return <div className="form-panel" role="status"><p className="eyebrow">SHOW YOUR ROUNDS</p><h2>APPLICATION RECEIVED.</h2><p>We review fighters individually and build matchups based on weight, experience, availability and compatibility.</p><p>Submitting an application does not guarantee a matchup. If selected, you will receive a confirmation link.</p>{youth&&<p>Your application requires guardian review before participation can be confirmed.</p>}<Link className="button red" href="/sessions">EXPLORE SESSIONS</Link></div>;
 if(!draft.ready)return <p role="status">Loading your application…</p>;
 return <form className="form-panel" onSubmit={submit} aria-busy={busy}>
  <p className="fine" role="status">{draft.unavailable?'This browser cannot save a draft. Keep this tab open until you finish.':draft.restored?'Your draft has been restored. You can continue where you left off.':'Your draft is saved in this tab for up to 24 hours, including after a page reload.'}</p>
  <p className="eyebrow">STEP {step+1} / 3</p><h2 ref={heading} tabIndex={-1}>{['START WITH YOU.','YOUR BOXING.','YOUR ROUNDS. YOUR CHOICE.'][step]}</h2>
  {!open&&<p className="notice">Applications are not open yet. You can explore the form; submission becomes available when registration opens.</p>}
  <div className="form-grid">
  {step===0&&<>{field('first_name','Legal first name')}{field('last_name','Legal last name')}{field('display_name','Public / display name')}{field('date_of_birth','Date of birth','date')}<p className="full">Age: {age??'Calculated from date of birth'}</p>{field('email','Email','email')}{field('phone','Phone','tel')}{field('instagram','Instagram handle','text',false)}{field('city','City')}{field('gym','Current gym')}{field('emergency_name','Emergency contact name')}{field('emergency_phone','Emergency contact phone','tel')}{youth&&<><p className="notice full">Under-18 applications require individual guardian review.</p>{field('guardian_name','Parent / guardian name')}{field('guardian_contact','Parent / guardian email or phone')}</>}</>}
  {step===1&&<><HeightSelect value={String(d.height||'')} onChange={value=>update('height',value)}/>{field('current_weight','Current weight (lb)','number',true,50,500)}{select('stance','Stance',['Orthodox','Southpaw','Switch'])}{field('years_boxing','Years boxing','number',true,0,90)}{select('competition_experience','Competition experience',['No fights','Amateur','Professional'])}{field('amateur_fights','Amateur fights','number',true,0,1000)}{field('professional_fights','Professional fights','number',true,0,1000)}{select('skill_level','Self-described skill level',['Beginner','Developing','Intermediate','Advanced','Competitive amateur','Professional'])}{area('sparring_experience','Sparring experience')}{select('preferred_intensity','Preferred sparring intensity',['Technical/light','Controlled/moderate','Competitive technical'])}{area('availability','Availability — days, times and dates')}{field('video_url','Link to boxing footage (HTTPS)','url',false)}<label>Requested session<select name="session_id" value={String(d.session_id)} onChange={e=>update('session_id',e.target.value)}><option value="">Any suitable upcoming session</option>{sessions.map(s=><option key={s.id} value={s.id}>{s.title} · {s.date}</option>)}</select></label>{area('notes','Additional notes',false)}</>}
  {step===2&&<><div className="full"><p>Your profile is part of your application. Contact details and date of birth are never shown publicly.</p><fieldset><legend>Profile and footage visibility</legend>{['PRIVATE','PUBLIC'].map(v=><label className="check-row" key={v}><input type="radio" name="visibility" value={v} checked={(youth?'PRIVATE':d.visibility)===v} disabled={youth} onChange={()=>update('visibility',v)}/><span><b>{v==='PUBLIC'?'Public':'Private'}</b><br/>{v==='PUBLIC'?'Eligible for publication after organizer review.':'Excluded from public profiles, channels and advertising.'}</span></label>)}</fieldset>
   {consent('no_guarantee_accepted','I understand submitting an application does not guarantee a matchup.')}
   {consent('accuracy_accepted','I confirm the information supplied is accurate.')}
   {consent('rules_accepted',<>I agree to the <Link href="/terms" target="_blank" rel="noreferrer">participation rules</Link> and have read the <Link href="/privacy" target="_blank" rel="noreferrer">privacy notice</Link>.</>)}
   {consent('recording_accepted','I understand Punch Mentality may record the session.')}
   {!youth&&d.visibility==='PUBLIC'&&consent('media_consent','I consent to publication of my approved profile and session footage on Punch Mentality’s website, social channels, YouTube and promotional materials, including advertising, as described in the participation rules.')}
   <p className="notice">Sparring participation is free. The $99 Punch Content Pack is optional and offered only after the matchup is confirmed. No payment with this application.</p></div></>}
  {step===2&&<label className="full">Profile photos (optional, up to 3)<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{const files=Array.from(e.target.files||[]);if(files.length>3||files.some(f=>f.size>5*1024*1024)){setError('Choose up to 3 photos, maximum 5 MB each.');e.target.value='';setPhotos([]);}else{setPhotos(files);setError('');}}}/><span>JPEG, PNG or WebP. First photo becomes your avatar. Photos follow your visibility choice and organizer review. Reselect photos after a page reload.</span>{photos.length>0&&<span>{photos.map(f=>f.name).join(', ')}</span>}</label>}
  </div><div className="honeypot" aria-hidden="true"><label>Leave empty<input name="website" tabIndex={-1} autoComplete="off" value={String(d.website)} onChange={e=>update('website',e.target.value)}/></label></div>
  {error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions">{step>0&&<button type="button" className="button outline" disabled={busy} onClick={()=>setStep(step-1)}>BACK</button>}<button className="button red" disabled={busy||(step===2&&!open)}>{busy?'SAVING…':step===2?'SUBMIT APPLICATION':'CONTINUE →'}</button></div>
 </form>;
}

