import Link from 'next/link';
import {sql} from '../../lib/postgres';
import Image from 'next/image';
import {notFound,permanentRedirect} from 'next/navigation';
import {publicFighters,publicMatchups,publicMedia,publicSessions} from '../../lib/public-data';
import MediaPlayer from '../../components/media-player';
import EventBeacon from '../../components/event-beacon';
export const dynamic='force-dynamic';
export default async function Fighter({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const fighters=await publicFighters();const f=fighters.find(f=>f.public_slug===slug);if(!f){const alias=(await sql().query('SELECT fighter_id FROM fighter_slug_aliases WHERE slug=$1',[slug])).rows[0];const approved=alias&&fighters.find(p=>p.id===alias.fighter_id);if(approved)permanentRedirect('/fighter/'+approved.public_slug);notFound();}const matches=(await publicMatchups()).filter(m=>[m.fighter_a_id,m.fighter_b_id].includes(f.id));const clips=(await sql().query('SELECT id,title,url FROM profile_media WHERE fighter_id=$1 AND published ORDER BY created_at DESC',[f.id])).rows;const sessions=await publicSessions();const media=await publicMedia();return <div className="shell workspace"><EventBeacon name="fighter_profile_viewed"/><p className="eyebrow">PUNCH FIGHTER PROFILE</p>{f.cover_photo_url&&<Image unoptimized width={1200} height={450} className="fighter-cover" src={f.cover_photo_url} alt={`${f.display_name} profile cover`}/>}<div className="fighter-public-identity">{f.profile_photo_url&&<Image unoptimized width={112} height={112} className="fighter-avatar" src={f.profile_photo_url} alt={f.display_name} referrerPolicy="no-referrer"/>}<h1>{f.display_name}</h1></div><p>{f.current_weight} LB · {f.stance} · {f.gym}</p><div className="profile-stats"><div><strong>{new Set(matches.map(m=>m.session_id)).size}</strong><span>PUNCH SESSIONS</span></div><div><strong>{matches.reduce((n,m)=>n+m.rounds,0)}</strong><span>DOCUMENTED ROUNDS</span></div></div><h2>SHOW YOUR ROUNDS.</h2>{clips.map(v=><MediaPlayer key={v.id} url={v.url} title={v.title}/>)}{matches.length===0&&<p>Published sessions will appear here.</p>}{matches.map(m=>{const s=sessions.find(s=>s.id===m.session_id);const other=fighters.find(f=>f.id===(m.fighter_a_id===f.id?m.fighter_b_id:m.fighter_a_id));return <article className="record-card" key={m.id}><h3><Link href={`/sessions/${s?.slug}`}>{s?.title}</Link></h3><p>{s?.date} · With {other?.display_name||'Punch participant'} · {m.rounds} rounds</p>{media.filter(v=>v.matchup_id===m.id&&(!v.fighter_id||v.fighter_id===f.id)).map(v=><MediaPlayer key={v.id} url={v.url} title={v.title}/>)}</article>;})}</div>;}

