import Link from 'next/link';
import Image from 'next/image';
import {notFound} from 'next/navigation';
import {publicFighters,publicMatchups,publicMedia,publicSessions} from '../../lib/public-data';
import MediaPlayer from '../../components/media-player';
import EventBeacon from '../../components/event-beacon';
export const dynamic='force-dynamic';
export default async function Fighter({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const fighters=await publicFighters();const f=fighters.find(f=>f.public_slug===slug);if(!f)notFound();const matches=(await publicMatchups()).filter(m=>[m.fighter_a_id,m.fighter_b_id].includes(f.id));const sessions=await publicSessions();const media=await publicMedia();return <div className="shell workspace"><EventBeacon name="fighter_profile_viewed"/><p className="eyebrow">PUNCH FIGHTER PROFILE</p>{f.profile_photo_url&&<Image unoptimized width={600} height={800} className="fighter-portrait" src={f.profile_photo_url} alt={f.display_name} referrerPolicy="no-referrer"/>}<h1>{f.display_name}</h1><p>{f.current_weight} LB · {f.stance} · {f.gym}</p><div className="profile-stats"><div><strong>{new Set(matches.map(m=>m.session_id)).size}</strong><span>PUNCH SESSIONS</span></div><div><strong>{matches.reduce((n,m)=>n+m.rounds,0)}</strong><span>DOCUMENTED ROUNDS</span></div></div><h2>SHOW YOUR ROUNDS.</h2>{matches.length===0&&<p>Published sessions will appear here.</p>}{matches.map(m=>{const s=sessions.find(s=>s.id===m.session_id);const other=fighters.find(f=>f.id===(m.fighter_a_id===f.id?m.fighter_b_id:m.fighter_a_id));return <article className="record-card" key={m.id}><h3><Link href={`/sessions/${s?.slug}`}>{s?.title}</Link></h3><p>{s?.date} · With {other?.display_name||'Punch participant'} · {m.rounds} rounds</p>{media.filter(v=>v.matchup_id===m.id&&(!v.fighter_id||v.fighter_id===f.id)).map(v=><MediaPlayer key={v.id} url={v.url} title={v.title}/>)}</article>;})}</div>;}

