import Link from 'next/link';
import {Button, Label, Photo} from '../components/ui';
const formats=[['01','Foundation','3 × 2','Building experience in controlled rounds.'],['02','Standard','3 × 3','For regular recreational and amateur sparring.'],['03','Competitive','4 × 3','Experienced amateurs. Coach approval required.']];
const prices=[{title:'Rounds',price:'$49–59',sub:'The essentials.',features:['Coach-approved pairing','Supervised sparring','Private full-round footage'],plan:'rounds'},{title:'Verified Session',price:'$79',sub:'The complete chapter.',features:['Everything in Rounds','Verified profile / history update','Coach notes or review','One approved social clip'],plan:'verified'},{title:'Content Session',price:'$109–129',sub:'More moments to keep.',features:['Everything in Verified Session','3–4 vertical edited clips','Publishing only with mutual consent'],plan:'content'}];
export default function Home(){return <main id="main">
 <section className="hero shell">
  <div className="hero-copy"><Label>VERIFIED BOXING DEVELOPMENT NETWORK</Label><h1>EVERY<br/>ROUND<br/><em>COUNTS.</em></h1><p className="hero-lead">Get the rounds.<br/>Keep the work.</p><p className="body-copy">Coach-approved sparring. Footage to study.<br className="desktop"/> A boxing history that grows with you.</p><div className="actions"><Button href="/request">Request rounds</Button><Link className="text-link" href="/profile">Explore the product <span>→</span></Link></div><div className="hero-foot">LOS ANGELES <span> / </span> 18+ <span> / </span> GYM & COACH LED</div></div>
  <div className="hero-visual"><Photo name="sparring-wide" alt="Two adult boxers practise a controlled jab in headgear as a coach observes" priority/><div className="photo-caption"><span>THE WORK, DOCUMENTED.</span><span>001 / LOS ANGELES</span></div><Link href="/session" className="floating-session"><div><span className="eyebrow">SAMPLE TRAINING CARD</span><strong>4 ROUNDS.<br/>ONE MORE CHAPTER.</strong></div><div className="floating-bottom"><span><i/> COACH VERIFIED · DEMO</span><b>↗</b></div></Link></div>
 </section>
 <div className="manifesto-strip"><div className="shell"><span>EXPERIENCE</span><i>+</i><span>CONTENT</span><i>+</i><span>DATA</span><small>ONE SESSION. THREE LASTING ASSETS.</small></div></div>
 <section className="section shell" id="system"><div className="section-heading"><Label>01 / THE IDEA</Label><h2>THE BELL RINGS.<br/><span>THE WORK STAYS.</span></h2><p>Sparring should not disappear when the bell rings. Every session adds to the boxer you are becoming.</p></div><div className="pillars">{[['01','Experience','Appropriate rounds.','Train with partners approved by a coach. Find variety across a trusted local gym network.'],['02','Content','Proof you can study.','Full rounds, selected clips and a closer look at what happened between the ropes.'],['03','Data','A history that means something.','Who you trained with, where, under which coach and for how many rounds. Verified over time.']].map(([n,title,sub,text])=><article key={n}><Label>{n} / {title}</Label><h3>{sub}</h3><p>{text}</p></article>)}</div></section>
 <section className="media-section"><div className="shell"><div className="section-heading"><Label>02 / YOUR SESSION, DELIVERED</Label><h2>NOT JUST A MEMORY.<br/>A BODY OF WORK.</h2><p>Full rounds for the study. Clips for the moments. Everything connected to one session.</p></div><div className="media-composition"><Link href="/session" className="round-preview"><div className="media-bar"><span>CAM 01 / FULL ROUNDS</span><span>PRIVATE BY DEFAULT ◉</span></div><Photo name="sparring-wide" alt="Sample full-round cover with both boxers and their coach"/><div className="media-bottom"><span>SESSION 010 <b>IMIN × JOHNSON</b></span><span>EXPLORE SESSION ↗</span></div></Link><Link href="/session?tab=clips" className="clip-preview"><Photo name="sparring-vertical" alt="Vertical cover of a technical jab and defensive guard"/><span className="clip-tag">9:16 / SELECTED CLIP</span><div className="clip-bottom"><span>THE SMALL<br/>THINGS ADD UP.</span><b>↗</b></div></Link></div><div className="media-caption"><span>SAMPLE SESSION · GENERATED IMAGERY · STILL PREVIEWS</span><span>Full rounds / Selected clips / Coach review / Session stills</span></div></div></section>
 <section className="section shell"><div className="section-heading"><Label>03 / THE PROCESS</Label><h2>GOOD ROUNDS.<br/>BY DESIGN.</h2><p>A coach has the final word. From your first request to the next session.</p></div><div className="process">{[['01','Request rounds','Tell us your weight, experience, gym and what you want to work on.'],['02','Coach approval','Your coach reviews the pairing, format and intensity before booking.'],['03','Check in & train','On-site weigh-in, verified check-in and supervised technical rounds.'],['04','Review. Return.','Private footage and a verified session. Request a rematch or a new partner.']].map(([n,title,text])=><article key={n}><span className="process-number">{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section className="passport-section"><div className="shell passport-promo"><div><Label>04 / YOUR FIGHTER PASSPORT</Label><h2>DON’T SAY<br/>YOU BOX.<br/><em>SHOW THE WORK.</em></h2><p>Rounds, sessions, styles faced. A record of your development, built through real participation.</p><Button href="/profile" secondary>Open sample passport</Button></div><Link href="/profile" className="passport-card"><div className="card-top"><Label>FIGHTER PASSPORT / SAMPLE</Label><span>↗</span></div><div className="passport-identity"><Photo name="fighter-white" alt="Generated sample fighter portrait in white training vest and headgear"/><div><span className="badge">✓ COACH VERIFIED · DEMO</span><h3>FARUKH<br/>IMIN</h3><p>176 LB · ORTHODOX<br/>LOS ANGELES, CA</p></div></div><div className="passport-numbers"><div><b>38</b><span>VERIFIED ROUNDS</span></div><div><b>10</b><span>SESSIONS</span></div><div><b>07</b><span>PARTNERS</span></div></div><div className="card-foot">YOUR BOXING HISTORY STARTS HERE. <span>↗</span></div></Link></div></section>
 <section className="section shell"><div className="section-heading"><Label>05 / FIND YOUR FORMAT</Label><h2>THE FORMAT CHANGES.<br/>THE STANDARD STAYS.</h2><p>Controlled, technical work at every level. Your coach approves the format for each pairing.</p></div><div className="formats">{formats.map(([n,title,rounds,note])=><article key={n}><Label>{n} / {title}</Label><strong>{rounds}<small>MIN</small></strong><p>{note}</p></article>)}</div></section>
 <section className="coach-feature shell"><Photo name="coach-review" alt="Boxer and coach review footage together on a tablet after training"/><div><Label>06 / COACH AUTHORITY</Label><h2>THE RIGHT EYES.<br/>ON YOUR ROUNDS.</h2><p>Coaches know the difference between more rounds and better rounds. They approve pairings, guide the session and help you understand the footage.</p><Link className="text-link" href="/coaches">Explore the coach workflow ↗</Link></div></section>
 <section className="section shell" id="pricing"><div className="section-heading"><Label>07 / PILOT PRICING CONCEPT</Label><h2>ONE SESSION.<br/>YOUR NEXT STEP.</h2><p>Pay per session. These are price hypotheses for feedback, not final offers. No payment is collected.</p></div><div className="pricing">{prices.map(({title,price,sub,features,plan})=><article key={title} className={plan==='verified'?'featured':''}><Label>{plan==='verified'?'THE CORE EXPERIENCE':'PER SESSION / ESTIMATE'}</Label><h3>{title}</h3><strong>{price}<small>USD</small></strong><p>{sub}</p><ul>{features.map(f=><li key={f}>✓ {f}</li>)}</ul><Button href={`/request?plan=${plan}`} secondary={plan!=='verified'}>Try this request</Button></article>)}</div></section>
 <section className="standards" id="standards"><div className="shell standards-grid"><div><Label>08 / THE CLUB STANDARD</Label><h2>CRAFT.<br/>CONTROL.<br/>RESPECT.</h2><Photo name="gear" alt="Headgear, gloves, wraps, mouthguard and boxing shoes arranged at ringside"/></div><div className="standard-list">{[['01','18+ public pilot','Los Angeles partner gyms. For adults already capable of supervised sparring.'],['02','Coach-led, always','Pairing approval, on-site weigh-in and coach check-in before every session.'],['03','Bring the right gear','Headgear, mouthguard, wraps and groin protection. 16 oz gloves by default; 14 oz only with coach approval.'],['04','Training, without scorecards','Controlled technical rounds. No winners, losers or public sparring rankings. A fighter or supervisor can stop the session.'],['05','Your footage. Your decision.','Full footage stays private by default. Publishing shared footage requires both fighters’ approval.']].map(([n,title,text])=><article key={n}><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>
 <section className="section shell faq"><Label>BEFORE YOUR FIRST ROUND</Label><h2>A FEW THINGS TO KNOW.</h2>{[['Do I need sparring experience?','The public pilot is for adults who already train at a gym and can participate in controlled sparring. Your coach reviews readiness and the appropriate format.'],['Does a request confirm my place?','No. In the pilot, a coach must approve the pairing and session details before booking. This prototype simulates that process and does not send a real request.'],['Will my footage be public?','Full footage is private by default. Shared clips and full sessions need mutual approval before public publishing.'],['Is this a fight or a tournament?','Neither. It is supervised training with no scoring, winner, loser or sparring win-loss record.'],['What happens after a session?','Your footage, session details and coach feedback become part of your development history. Request another partner or arrange a rematch through the same coach approval process.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section>
 <section className="final-cta"><div className="shell"><Label>YOUR NEXT CHAPTER / LOS ANGELES</Label><h2>PUT IN THE ROUNDS.<br/>KEEP THE PROGRESS.</h2><Button href="/request">Request rounds</Button><p>18+ · Coach approval required · Interactive prototype</p></div></section>
 </main>}
