import Link from 'next/link';
import UpdatesForm from './components/updates-form';
import Image from 'next/image';
import HeroBackground from './components/hero-background';
import {Arrow,ProfileCard} from './components/ui';
import {publicSessions,publicFighters,publicMedia} from './lib/public-data';
import MediaPlayer from './components/media-player';
export const dynamic='force-dynamic';
const faqs=[
 ['Is sparring free?','Yes. Approved sparring participation is currently free. Buying content is optional and never affects eligibility.'],
 ['How do I get matched?','Apply with your age, weight, experience, skill and availability. Our team reviews applications individually and builds pairings with coach judgment. There is no automated matching.'],
 ['Does applying guarantee a place?','No. If a suitable pairing is available, you will receive a private invitation with session information and confirmation options.'],
 ['When can I buy the Content Pack?','Only after both fighters confirm the matchup. The founding price is $99 per fighter. You can decline the package and still spar.'],
 ['What does the Content Pack include?','A full multicamera edit of your sparring, a personal highlight, a vertical social reel and the session added to your Punch profile.'],
 ['Will my footage be public?','You choose Public or Private in the application. Public use requires media consent and organizer review. Shared footage requires publication permission from both fighters.'],
 ['Can someone under 18 apply?','Under-18 applications are flagged for individual guardian review. No matchup can be created until the required guardian review is completed. Youth profiles and footage are not published in this MVP.'],
 ['What equipment do I need?','Headgear, mouthguard, wraps, groin protection and suitable gloves. 16 oz is the default; 14 oz requires coach approval. Final gear and readiness checks happen on site.'],
];
export default async function Home(){const sessions=await publicSessions();const next=sessions.filter(s=>s.status==='UPCOMING'&&s.date>=new Date().toISOString().slice(0,10)).sort((a,b)=>a.date.localeCompare(b.date))[0];const fighters=(await publicFighters()).slice(0,4);const media=(await publicMedia()).slice(0,2);
 return <><section className="hero" id="top"><HeroBackground/><div className="shell hero-inner"><div className="hero-kicker mono"><span className="red-rule"/> LOS ANGELES <span className="hero-kicker-end">CURATED TECHNICAL SPARRING</span></div><div className="hero-copy"><h1>TECHNICAL<br/>SPARRING.<br/><span>DOCUMENTED.</span></h1><p>Curated technical sparring sessions in Los Angeles.<br/>Matched by weight and experience. Professional production.<br/>Build a documented record of your rounds.</p><div className="actions"><Link className="button red" href="/apply">APPLY TO SPAR <Arrow/></Link><Link className="button outline" href="/watch">WATCH SESSIONS <Arrow/></Link></div><div className="hero-offers"><span>SPARRING <b>FREE</b></span><span>OPTIONAL CONTENT PACK <b>$99</b></span></div><p className="hero-note">No payment to apply. Every matchup is reviewed.</p></div><div className="hero-bottom mono"><span>SHOW YOUR ROUNDS.</span><span>INSIDE DALAKIAN</span></div></div></section>
 <div className="principles-strip"><div className="shell"><span>CURATED TECHNICAL SPARRING</span><span>REAL ROUNDS</span><span>PROFESSIONAL PRODUCTION</span></div></div>
 <section className="editorial-section" id="experience"><div className="shell"><p className="eyebrow">01 / THE COMMUNITY</p><h2>REAL WORK.<br/>A LASTING RECORD.</h2><p className="section-lead">Punch Mentality brings Los Angeles fighters together for controlled, coach-supervised rounds. We organize the pairing and document the work, so you can study it, share it and build on it.</p></div></section>
 <section className="editorial-section gym-home"><div className="shell gym-story"><Image src="/images/gym/PM-02-Ring-front.webp" width={2200} height={1467} alt="Dalakian boxing ring viewed from the training floor" sizes="(max-width: 760px) 92vw, 55vw"/><div><p className="eyebrow">INSIDE THE GYM</p><h2>THE SPACE.<br/>THE PEOPLE.<br/>THE WORK.</h2><p>Step inside Dalakian Elite Boxing &amp; Fitness. Meet Artem and see the training floor through our photographs.</p><Link className="button outline" href="/gym">EXPLORE THE GYM <Arrow/></Link></div></div></section><section className="editorial-section bone-section" id="how"><div className="shell"><p className="eyebrow">02 / HOW IT WORKS</p><h2>FROM APPLICATION<br/>TO ROUNDS.</h2><div className="steps-grid">{[['APPLY','Tell us about your weight, experience, gym and availability.'],['GET MATCHED','Our team reviews compatibility. Confirm through your private invitation.'],['SPAR','Check in, weigh in and work under coach/referee supervision.'],['BUILD YOUR RECORD','Keep a history of your rounds. Add professional footage with the optional Content Pack.']].map(([t,p],i)=><article key={t}><p className="eyebrow">0{i+1}</p><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>
 <section className="editorial-section" id="next"><div className="shell"><p className="eyebrow">03 / NEXT SESSION</p><h2>{next?.title||'THE NEXT ROUNDS.'}</h2><p>{next?`${next.date} · ${next.start_time} · ${next.location_name}, ${next.city}`:'The next date and location will be announced here.'}</p><p>{next?.description||'Apply for future sessions. We will contact you when a suitable pairing is available.'}</p><div className="actions"><Link className="button red" href={next?`/apply?session=${next.id}`:'/apply'}>APPLY TO SPAR <Arrow/></Link><Link href="/sessions" className="button outline">ALL SESSIONS</Link></div></div></section>
 <section className="editorial-section bone-section" id="footage"><div className="shell"><p className="eyebrow">04 / THE BODY OF WORK</p><h2>RECENT FIGHTERS.<br/>RECENT ROUNDS.</h2><div className="record-list">{fighters.map(f=><article key={f.id}><h3><Link href={`/fighter/${f.public_slug}`}>{f.display_name}</Link></h3><p>{f.current_weight} LB · {f.stance} · {f.gym}</p></article>)}{media.map(v=><MediaPlayer key={v.id} url={v.url} title={v.title}/>)}</div>{!fighters.length&&!media.length&&<p>Approved fighter profiles and authentic Punch footage will appear after the first published sessions.</p>}<Link className="button outline" href="/watch">WATCH THE ROUNDS <Arrow/></Link></div></section>
 <section className="editorial-section" id="pricing"><div className="shell content-pack-layout"><div><p className="eyebrow">05 / OPTIONAL PRODUCTION</p><h2>PUNCH<br/>CONTENT PACK.</h2><p className="pack-price">$99 <small>FOUNDING PRICE / FIGHTER</small></p><p>Sparring participation is free.<br/>Purchasing content is optional.</p><Link href="/apply" className="button red">APPLY TO SPAR <Arrow/></Link><p className="fine">The Content Pack is offered after your matchup is confirmed. No payment during application.</p></div><div className="pack-inclusions">{[['FULL ROUNDS','Professional multicamera edit of your complete sparring session.'],['PERSONAL HIGHLIGHT','Your best sequences, centered on your movement and technique.'],['SOCIAL REEL','A vertical edit ready for Instagram and TikTok.'],['PUNCH PROFILE','Your session added to your documented Punch record.']].map(([t,p])=><article key={t}><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>
 <section className="editorial-section bone-section"><div className="shell content-pack-layout"><div><p className="eyebrow">06 / YOUR FIGHTER PROFILE</p><h2>SHOW<br/>YOUR ROUNDS.</h2><p>Sessions. Documented rounds. Progress. Footage.</p><p>No unofficial win-loss record. Your profile documents the work you put in.</p></div><ProfileCard/></div></section>
 <section className="editorial-section philosophy"><div className="shell"><p className="eyebrow">07 / THE MENTALITY</p><h2>CLARITY<br/>UNDER PRESSURE.</h2><p>Good rounds ask for control, attention and respect.<br/>Show up to learn. Leave with something to build on.</p></div></section>
 <section className="editorial-section bone-section" id="faq"><div className="shell"><h2>BEFORE THE BELL.</h2>{faqs.map(([q,a])=><details className="faq-item" key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
 <section className="editorial-section bone-section" id="updates"><div className="shell"><p className="eyebrow">STAY IN THE CORNER</p><h2>THE NEXT ROUNDS.<br/>IN YOUR INBOX.</h2><UpdatesForm/></div></section><section className="editorial-section final-apply"><div className="shell"><p className="eyebrow">LOS ANGELES / PUNCH MENTALITY</p><h2>YOUR NEXT<br/>ROUNDS START HERE.</h2><Link className="button cream" href="/apply">APPLY TO SPAR <Arrow/></Link></div></section></>;
}


