'use client';
import {FormEvent,useEffect,useRef,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {Button,DemoNote,Label,Photo} from './ui';
import {plans,sessions} from '../lib/demo';
const empty={name:'',email:'',age:'',weight:'',height:'',stance:'Orthodox',experience:'',sparring:'',gym:'',coach:'',date:'',time:'Evening',intensity:'Technical / controlled',style:'No preference',tape:'',goal:'',plan:'verified'};
const heightOptions=Array.from({length:65},(_,i)=>i+36);
const formatHeight=(inches:number)=>`${Math.floor(inches/12)}′ ${inches%12}″ (${Math.floor(inches/12)} ft ${inches%12} in)`;
const checks=['I confirm I am 18 or older.','I will bring headgear, mouthguard, wraps, groin protection and sparring gloves. 16 oz is the default; 14 oz requires coach approval.','I understand that participation and pairing require coach approval, on-site weigh-in and coach check-in.'];
export default function RequestFlow(){
 const params=useSearchParams();const [step,setStep]=useState(0);const [data,setData]=useState(empty);const [agreed,setAgreed]=useState([false,false,false]);const [done,setDone]=useState(false);const [error,setError]=useState('');const [today,setToday]=useState('');const title=useRef<HTMLHeadingElement>(null);const intent=params.get('intent');const partner=(sessions.find(s=>s.id===params.get('session'))||sessions[0]).partner;
 useEffect(()=>{const now=new Date();setToday(`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`);const p=params.get('plan');if(p && p in plans)setData(d=>({...d,plan:p}));},[params]);
 useEffect(()=>{if(step>0||done)title.current?.focus();},[step,done]);
 function change(name:keyof typeof empty,value:string){setData(d=>({...d,[name]:value}));setError('');}
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!agreed.every(Boolean)){setError('Please confirm all three participation requirements.');return;}if(step===2&&data.date<today){setError('Choose today or a future date.');return;}if(step<3){setStep(step+1);return;}try{sessionStorage.setItem('pm-v2-request',JSON.stringify({version:1,type:'prototype',intent:intent||'new-rounds',partner:intent==='rematch'?partner:null,...data,createdAt:new Date().toISOString()}));setDone(true);}catch{setError('This browser could not save the demo request. Allow session storage and try again. Your entries are still here.');}}
 const field=(key:keyof typeof empty,label:string,type='text',required=true,extra:Record<string,string|number>={})=><label>{label}{required?' *':''}<input name={key} type={type} value={data[key]} onChange={e=>change(key,e.target.value)} required={required} {...extra}/></label>;
 const select=(key:keyof typeof empty,label:string,options:string[])=><label>{label} *<select name={key} value={data[key]} onChange={e=>change(key,e.target.value)} required><option value="" disabled>Select an option</option>{options.map(o=><option key={o}>{o}</option>)}</select></label>;
 return <><DemoNote/><div className="request-layout"><aside className="request-intro"><Label>LOS ANGELES / REQUEST ROUNDS</Label><h1>YOUR NEXT<br/>ROUND<br/><em>STARTS HERE.</em></h1><p>{intent==='rematch'?`Same partner. A new chapter. Request another session with ${partner}.`:intent==='new-partner'?'A different style. A new perspective. Tell your coach what you want to work on.':'Tell us about your boxing. A coach reviews the pairing before any session is confirmed.'}</p><Photo name="fighter-black" alt="Sample boxer in black training vest and protective headgear"/><div className="fineprint">PROTOTYPE ONLY. Use sample details. Your demo request stays in this browser tab for this session. Nothing is sent to a coach.</div></aside><section className="request-panel">{done?<div className="request-success"><span className="large-check">✓</span><Label>DEMO REQUEST SAVED</Label><h2 ref={title} tabIndex={-1}>NEXT UP:<br/>COACH REVIEW.</h2><p>Your sample request for {data.date} is saved in this browser tab. No real application was sent and no place is booked.</p><div className="receipt"><strong>{data.name}</strong><span>{data.weight} LB · {data.stance}</span><span>{data.gym}</span><span>{plans[data.plan as keyof typeof plans]}</span><span className="badge">AWAITING COACH REVIEW · DEMO</span></div><ol className="next-steps"><li>Coach reviews experience and pairing.</li><li>Approved partners confirm session details.</li><li>Weigh-in and check-in happen at the gym.</li></ol><Button href="/session?view=checkin">Explore the session workflow</Button><button className="text-button" onClick={()=>{setDone(false);setStep(1)}}>Edit demo request</button><button className="text-button" onClick={()=>{try{sessionStorage.removeItem('pm-v2-request')}catch{}setData(empty);setAgreed([false,false,false]);setStep(0);setDone(false)}}>Clear saved demo</button></div>:<><div className="form-steps" aria-label="Request progress">{['Standards','Fighter','Rounds','Review'].map((s,i)=><span key={s} aria-current={step===i?'step':undefined} className={i<=step?'active':''}><b>0{i+1}</b>{s}</span>)}</div><form onSubmit={submit}>
 {step===0&&<><Label>01 / BEFORE YOU APPLY</Label><h2 ref={title} tabIndex={-1}>SAME STANDARD.<br/>EVERY ROUND.</h2><p>Controlled technical sparring. Coach supervision. Respect for your partner.</p><div className="checklist">{checks.map((text,i)=><label className="checkbox-label" key={text}><input type="checkbox" checked={agreed[i]} onChange={e=>setAgreed(a=>a.map((v,j)=>j===i?e.target.checked:v))} required/><span>{text}</span></label>)}</div><div className="privacy-callout"><b>PRIVATE FIRST.</b><p>Full footage stays private by default. These confirmations do not grant permission to publish. Public content requires a separate mutual approval.</p></div><p className="fineprint">Select all three confirmations to continue.</p></>}
 {step===1&&<><Label>02 / YOUR FIGHTER DETAILS</Label><h2 ref={title} tabIndex={-1}>TELL US ABOUT<br/>YOUR BOXING.</h2><div className="form-grid">{field('name','Full name')}{field('age','Age','number',true,{min:18,max:100})}{field('email','Email','email')}{field('weight','Current weight / lb','number',true,{min:70,max:500,step:0.1})}<label>Height / ft &amp; in<select name="height" value={data.height} onChange={e=>change('height',e.target.value)}><option value="">Select height (optional)</option>{heightOptions.map(inches=><option key={inches} value={inches}>{formatHeight(inches)}</option>)}</select></label>{select('stance','Stance',['Orthodox','Southpaw','Switch'])}{select('experience','Boxing experience',['Under 1 year','1–2 years','3–5 years','5+ years'])}{select('sparring','Sparring experience',['Coach-cleared, first sessions','Occasional supervised rounds','Regular supervised sparring','Experienced amateur'])}{field('gym','Home gym')}{field('coach','Coach name','text',false)}</div><p className="fineprint">Already training at a gym and able to spar under supervision. Readiness is always reviewed by a coach.</p></>}
 {step===2&&<><Label>03 / THE ROUNDS YOU NEED</Label><h2 ref={title} tabIndex={-1}>MAKE THE<br/>WORK COUNT.</h2><div className="form-grid">{field('date','Preferred date','date',true,{min:today})}{select('time','Preferred time / Los Angeles',['Morning','Afternoon','Evening'])}{select('intensity','Preferred intensity',['Technical / controlled','Light technical','Coach decides'])}{select('style','Preferred partner style',['No preference','Southpaw','Orthodox','Pressure','Counter','Outside'])}</div>{field('tape','Video / tape link','url',false,{placeholder:'https://…'})}<label>What do you want to work on?<textarea value={data.goal} onChange={e=>change('goal',e.target.value)} placeholder="Timing, defense, exits, working with a southpaw…" maxLength={1200}/></label><label>Session package · price hypothesis<select value={data.plan} onChange={e=>change('plan',e.target.value)}>{Object.entries(plans).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><p className="fineprint">No payment. Final format, pairing and availability depend on coach approval.</p></>}
 {step===3&&<><Label>04 / CHECK YOUR REQUEST</Label><h2 ref={title} tabIndex={-1}>READY FOR<br/>A COACH’S EYES.</h2><dl className="review-list">{[['Fighter',`${data.name} · ${data.age}`],['Email',data.email],['Boxing',`${data.weight} LB · ${data.stance} · ${data.experience}`],['Height',data.height?formatHeight(Number(data.height)):'Not provided'],['Sparring',data.sparring],['Home gym',data.gym],['Preference',`${data.date} · ${data.time} (Los Angeles)`],['Intensity',data.intensity],['Partner',intent==='rematch'?`${partner} · rematch`:data.style],['Package',plans[data.plan as keyof typeof plans]],['Footage','Private by default']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="privacy-callout">This saves a demo request in this browser tab only. It does not submit a live application, confirm a booking or charge a payment.</div></>}
 {error&&<p role="alert" className="error-message">{error}</p>}<div className="form-actions">{step>0?<button type="button" className="text-button" onClick={()=>setStep(step-1)}>← Back</button>:<span>18+ / LOS ANGELES</span>}<button type="submit" className="button" disabled={step===0&&!agreed.every(Boolean)}>{step===3?'Save demo request':'Continue'} <span>→</span></button></div></form></>}</section></div></>;
}
