'use client';
import {useEffect,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {Button,DemoNote,Label,Photo} from './ui';
import {sessions} from '../lib/demo';
const stages=['Request rounds','Coach approval','Session booking','Verified check-in','Supervised rounds','Video upload','Verified session'];
export default function SessionView(){
 const params=useSearchParams();const session=sessions.find(s=>s.id===params.get('id'))||sessions[0];const [tab,setTab]=useState('rounds');const [round,setRound]=useState(1);const [camera,setCamera]=useState(1);const [demoStage,setDemoStage]=useState(6);const [checkin,setCheckin]=useState([false,false,false]);const [coachAccess,setCoachAccess]=useState(true);const [clipConsent,setClipConsent]=useState([false,false]);const [fullConsent,setFullConsent]=useState([false,false]);const [share,setShare]=useState('');const [linkEnabled,setLinkEnabled]=useState(false);
 useEffect(()=>{if(params.get('tab')==='clips')setTab('clips');if(params.get('view')==='checkin')setDemoStage(0);},[params]);
 async function copyClip(){try{await navigator.clipboard.writeText(`${window.location.origin}/session?tab=clips&id=${session.id}`);setShare('Demo page link copied. This links to the prototype, not published footage.');}catch{setShare('Copy is unavailable in this browser. The demo page address is shown below.');}}
 useEffect(()=>{setRound(1);setCamera(1);setClipConsent([false,false]);setFullConsent([false,false]);setLinkEnabled(false);setShare('');},[session.id]);
 const ready=demoStage===6;
 return <><DemoNote/><div className="session-title"><div><Label>TRAINING CARD / SESSION {session.id} / {session.date}</Label><h1>IMIN <span>×</span><br className="mobile"/>{session.partner.split(' ').at(-1)?.toUpperCase()}</h1></div><span className={`session-seal ${ready?'':'pending'}`}>{ready?'✓':'◷'}<b>{ready?'SESSION COMPLETE':'SESSION IN PROGRESS'}</b><small>{ready?'VERIFIED · SAMPLE':'SIMULATED WORKFLOW'}</small></span></div><div className="session-meta"><div><Label>SESSION WEIGHT</Label><b>176 LB</b></div><div><Label>FORMAT</Label><b>{session.rounds} × {session.minutes} MIN</b></div><div><Label>GYM</Label><b>{session.gym}</b></div><div><Label>COACH</Label><b>{session.coach}</b></div><div><Label>INTENSITY</Label><b>Technical / controlled</b></div></div>
 <section className="session-workflow"><div className="small-heading"><Label>THE VERIFICATION TRAIL</Label><button className="text-button" onClick={()=>{setDemoStage(0);setCheckin([false,false,false]);setClipConsent([false,false]);setFullConsent([false,false]);setLinkEnabled(false);setShare('')}}>Try check-in demo ↺</button></div><ol>{stages.map((s,i)=><li className={i<=demoStage?'complete':''} key={s}><span>{i<demoStage||ready?'✓':String(i+1).padStart(2,'0')}</span>{s}</li>)}</ol>{!ready&&<div className="checkin-demo"><div><Label>SIMULATION / {stages[demoStage]}</Label><h3>{['A request is ready for review.','The coach approves this pairing.','Both fighters confirm session details.','Verify attendance at the gym.','Controlled rounds, supervised.','Attach footage to the session.'][demoStage]}</h3><p>{['The coach checks experience, size and goals.','Approval covers the pairing, format and intensity.','A booking still requires on-site weigh-in and coach check-in.','In the pilot a coach can check fighters in manually. QR check-in can open this same workflow; no real QR scanner is connected here.','The supervising coach confirms the session has ended.','Private footage and coach confirmation complete the verification trail. No video is uploaded in this demo.'][demoStage]}</p></div><div>{demoStage===3&&<div className="checklist">{['Both fighters present / check-in confirmed','On-site weight checked','Coach clears pairing and equipment'].map((s,i)=><label className="checkbox-label" key={s}><input type="checkbox" checked={checkin[i]} onChange={e=>setCheckin(v=>v.map((x,j)=>i===j?e.target.checked:x))}/><span>{s}</span></label>)}</div>}<button className="button" disabled={demoStage===3&&!checkin.every(Boolean)} onClick={()=>setDemoStage(s=>s+1)}>{['Simulate coach review','Simulate pairing approval','Simulate booking','Confirm demo check-in','Confirm rounds complete','Simulate footage & verification'][demoStage]} →</button><p className="fineprint">DEMO ACTION · NO REAL ATTENDANCE OR APPROVAL</p></div></div>}</section>
 <section className="session-content"><div className="tabs" aria-label="Session materials">{[['rounds','Full rounds'],['clips','Selected clips'],['review','Coach review'],['stills','Session stills']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>{tab==='rounds'&&<div className="rounds-layout"><div><div className="media-bar"><span>CAM {camera===1?'01':'02'} / ROUND {round}</span><span>PRIVATE FULL FOOTAGE</span></div><Photo name={camera===1?'sparring-wide':'sparring-editorial'} alt={`Illustrative camera ${camera} angle for round ${round}`}/><div className="media-bar"><span>STILL PREVIEW / NO VIDEO ATTACHED</span><span>{session.minutes}:00 ROUND FORMAT</span></div></div><aside className="round-selector"><Label>THE FULL SESSION</Label><h3>EVERY ROUND.<br/>YOURS TO STUDY.</h3><p>Select a round or camera to explore the media layout. Covers are illustrative stills.</p><div className="camera-toggle">{[1,2].map(c=><button key={c} aria-pressed={camera===c} onClick={()=>setCamera(c)}>CAM {c}</button>)}</div>{Array.from({length:session.rounds},(_,i)=><button className="round-button" key={i} aria-pressed={round===i+1} onClick={()=>setRound(i+1)}><span>ROUND 0{i+1}</span><span>{session.minutes}:00 <b>↗</b></span></button>)}</aside></div>}
 {tab==='clips'&&<div className="clips-layout"><Photo name="sparring-vertical" alt="Selected technical exchange shown as a vertical still"/><div><Label>SELECTED CLIP / 9:16</Label><h2>THE DETAILS<br/>MAKE THE DIFFERENCE.</h2><p>A compact jab. A balanced guard. A moment worth revisiting.</p><span className="badge">{clipConsent.every(Boolean)?'MUTUAL APPROVAL · DEMO':'PRIVATE · AWAITING MUTUAL APPROVAL'}</span><p className="fineprint">Sample cover only. No edited video is attached. Sharing controls below demonstrate the approval process.</p><a href="#privacy" className="text-link">Review clip permissions ↓</a></div></div>}
 {tab==='review'&&<div className="coach-review-layout"><Photo name="coach-review" alt="Coach and fighter looking at a tablet together"/><div><Label>COACH {session.coach.toUpperCase()} / SAMPLE NOTES</Label><h2>REVIEW THE WORK.</h2>{[['What worked','The jab maintained distance. You stayed balanced when resetting.'],['Keep working','Return the rear hand to guard before changing your angle.'],['Next session focus','Exit after the jab. Reset your feet before the next exchange.']].map(([title,text])=><div className="coach-note" key={title}><b>{title}</b><p>{text}</p></div>)}</div></div>}
 {tab==='stills'&&<div className="stills-grid">{[['sparring-wide','The round'],['wraps','The preparation'],['coach-review','The review']].map(([name,caption])=><figure key={name}><Photo name={name} alt={`Generated sample still: ${caption}`}/><figcaption>{caption} / Sample still</figcaption></figure>)}</div>}</section>
 <section className="privacy-panel" id="privacy"><div className="privacy-intro"><Label>YOUR TRAINING. YOUR DECISION.</Label><h2>PRIVATE<br/>UNTIL YOU<br/><em>DECIDE.</em></h2><p>Full footage stays private by default. Content involving both fighters requires mutual approval.</p><p className="fineprint">These controls simulate permission states. No real access is granted and no footage is published. AI analysis and model training are outside this MVP and would require separate opt-in.</p></div><div className="permission-list"><div className="permission-row"><div><h3>Private full footage</h3><p>Visible to the session’s participants in the planned product.</p></div><span className="badge">PRIVATE</span></div><div className="permission-row"><div><h3>Coach access</h3><p>{coachAccess?'Assigned coach can review · Demo':'Coach access removed · Demo'}</p></div><button className="switch" role="switch" aria-checked={coachAccess} aria-label="Coach access" onClick={()=>setCoachAccess(!coachAccess)}><span/></button></div><div className="permission-row"><div><h3>Share link</h3><p>{linkEnabled?'Sample access-link state enabled. No media link is created.':'Off by default. Any shared footage still requires mutual approval.'}</p></div><button className="switch" role="switch" aria-checked={linkEnabled} aria-label="Share link" disabled={!clipConsent.every(Boolean)} onClick={()=>setLinkEnabled(!linkEnabled)}><span/></button></div><div className="consent-group"><h3>Public highlights</h3><p>Try both consent states. These are simulated decisions.</p>{['Fighter A approves clips · Demo','Fighter B approves clips · Demo'].map((l,i)=><label className="checkbox-label" key={l}><input type="checkbox" checked={clipConsent[i]} onChange={e=>{setClipConsent(c=>c.map((v,j)=>i===j?e.target.checked:v));setLinkEnabled(false);setShare('')}}/><span>{l}</span></label>)}<div className="consent-status" role="status">{clipConsent.every(Boolean)?'✓ Both approved in demo. Clip sharing is available.':'Private. Both fighters must approve before sharing.'}</div><button className="button secondary" disabled={!clipConsent.every(Boolean)||!ready} onClick={copyClip}>Share approved clip · Demo ↗</button>{share&&<div className="share-status" role="status">{share}<br/><code>/session?tab=clips&id={session.id}</code></div>}</div><div className="consent-group"><h3>Public full session</h3><p>Separate permission. Clip approval never makes the full session public.</p>{['Fighter A approves full session · Demo','Fighter B approves full session · Demo'].map((l,i)=><label className="checkbox-label" key={l}><input type="checkbox" checked={fullConsent[i]} onChange={e=>setFullConsent(c=>c.map((v,j)=>i===j?e.target.checked:v))}/><span>{l}</span></label>)}<div className="consent-status" role="status">{fullConsent.every(Boolean)?'Mutual approval recorded in demo. No publication takes place.':'Full session remains private.'}</div></div></div></section>
 <section className="session-next"><div><Label>{ready?'SESSION COMPLETE / KEEP BUILDING':'YOUR NEXT STEP'}</Label><h2>ANOTHER ROUND.<br/>ANOTHER CHAPTER.</h2><p>A verified session belongs in both fighters’ histories.</p></div><div className="actions"><Button href={`/request?intent=rematch&session=${session.id}`}>Request rematch</Button><Button href="/request?intent=new-partner" secondary>Request new partner</Button><Button href="/profile" secondary>View fighter passport</Button></div></section></>;
}
