import assert from 'node:assert/strict';
import {test} from 'node:test';
import {applicationSchema,contactSchema} from '../app/lib/validation';
const base={request_id:'912f1b4c-3775-4bc6-8718-ea31ad3c1922',lead_token:'a'.repeat(64),first_name:'QA',last_name:'Test',instagram:'qa_boxer',email:'qa@example.com',phone:'2025550123',date_of_birth:'1995-04-12',city:'Los Angeles',height:70,current_weight:175,stance:'Orthodox',years_boxing:3,competition_experience:'No fights',amateur_fights:0,professional_fights:2,sparring_experience:'Weekly',skill_level:'Intermediate',preferred_intensity:'Technical/light',availability:'Weekend mornings',visibility:'PUBLIC',media_consent:true,rules_accepted:true,accuracy_accepted:true,no_guarantee_accepted:true,recording_accepted:true};
test('minimal adult application accepts missing optional fields and professional fights',()=>{const v=applicationSchema.parse(base);assert.equal(v.display_name,'QA');assert.equal(v.competition_experience,'Professional');assert.equal(v.emergency_phone,'');});
test('invalid calendar date and experience rejected',()=>{assert.equal(contactSchema.safeParse({...base,date_of_birth:'2000-02-31'}).success,false);assert.equal(applicationSchema.safeParse({...base,years_boxing:90}).success,false);});
test('minor needs guardian review details',()=>{assert.equal(applicationSchema.safeParse({...base,date_of_birth:'2012-04-12',visibility:'PRIVATE',media_consent:false}).success,false);assert.equal(applicationSchema.safeParse({...base,date_of_birth:'2012-04-12',visibility:'PRIVATE',media_consent:false,guardian_name:'Guardian',guardian_contact:'2025550124'}).success,true);});
test('marketing is not implicit and spam field rejected',()=>{assert.equal(contactSchema.parse(base).marketing_consent,false);assert.equal(contactSchema.safeParse({...base,website:'spam'}).success,false);});

test('last name is required for both contact and final application',()=>{for(const last_name of ['', '   ', undefined]){assert.equal(contactSchema.safeParse({...base,last_name}).success,false);assert.equal(applicationSchema.safeParse({...base,last_name}).success,false);}});

test('Instagram is required and normalizes handles and profile links',()=>{for(const instagram of ['', 'https://evil.example/x','bad handle'])assert.equal(applicationSchema.safeParse({...base,instagram}).success,false);assert.equal(applicationSchema.parse({...base,instagram:'https://www.instagram.com/qa_boxer/'}).instagram,'qa_boxer');assert.equal(applicationSchema.parse({...base,instagram:'@qa_boxer'}).instagram,'qa_boxer');});
